//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Snoopi.web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Advertisements {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Advertisements() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Snoopi.web.Resources.Advertisements", typeof(Advertisements).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to פרסומת.
        /// </summary>
        internal static string AdPic {
            get {
                return ResourceManager.GetString("AdPic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מס&apos; תוצאות.
        /// </summary>
        internal static string AdsCountLabel {
            get {
                return ResourceManager.GetString("AdsCountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to פרסומות.
        /// </summary>
        internal static string AllAds {
            get {
                return ResourceManager.GetString("AllAds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to חברות מפרסמות.
        /// </summary>
        internal static string AllCompanies {
            get {
                return ResourceManager.GetString("AllCompanies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to באנר.
        /// </summary>
        internal static string Bunner {
            get {
                return ResourceManager.GetString("Bunner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שם חברה.
        /// </summary>
        internal static string BusinessName {
            get {
                return ResourceManager.GetString("BusinessName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to חברה.
        /// </summary>
        internal static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to האם אתה בטוח שברצונך למחוק את החברה?.
        /// </summary>
        internal static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תאריך יצירה.
        /// </summary>
        internal static string CreateDate {
            get {
                return ResourceManager.GetString("CreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מחק תמונה.
        /// </summary>
        internal static string DeleteImage {
            get {
                return ResourceManager.GetString("DeleteImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to פרסומת נמחקה בהצלחה.
        /// </summary>
        internal static string DeleteMessage {
            get {
                return ResourceManager.GetString("DeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to עריכת חברה מפרסמת.
        /// </summary>
        internal static string EditAdCompanyPageTitle {
            get {
                return ResourceManager.GetString("EditAdCompanyPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to עריכת פרסומת.
        /// </summary>
        internal static string EditAdPageTitle {
            get {
                return ResourceManager.GetString("EditAdPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to קובץ.
        /// </summary>
        internal static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מתאריך.
        /// </summary>
        internal static string FromDate {
            get {
                return ResourceManager.GetString("FromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to דף הבית שמאל.
        /// </summary>
        internal static string home_page_left {
            get {
                return ResourceManager.GetString("home_page_left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to דף הבית ימין.
        /// </summary>
        internal static string home_page_right {
            get {
                return ResourceManager.GetString("home_page_right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to דף הבית עליון.
        /// </summary>
        internal static string home_page_top {
            get {
                return ResourceManager.GetString("home_page_top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to פרסומת נוצרה בהצלחה.
        /// </summary>
        internal static string MessageAdCreated {
            get {
                return ResourceManager.GetString("MessageAdCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to פרסומת נשמרה בהצלחה.
        /// </summary>
        internal static string MessageAdSaved {
            get {
                return ResourceManager.GetString("MessageAdSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to חברה נוצרה בהצלחה.
        /// </summary>
        internal static string MessageCompanyCreated {
            get {
                return ResourceManager.GetString("MessageCompanyCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לא נמצאו פרסומות.
        /// </summary>
        internal static string MessageNoAdsFound {
            get {
                return ResourceManager.GetString("MessageNoAdsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לא נמצאו חברות.
        /// </summary>
        internal static string MessageNoCompaniesFound {
            get {
                return ResourceManager.GetString("MessageNoCompaniesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to חברה מפרסמת חדשה.
        /// </summary>
        internal static string NewAdCompanyPageTitle {
            get {
                return ResourceManager.GetString("NewAdCompanyPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to פרסומת חדשה.
        /// </summary>
        internal static string NewAdPageTitle {
            get {
                return ResourceManager.GetString("NewAdPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to דפים פנימיים שמאל.
        /// </summary>
        internal static string page_left {
            get {
                return ResourceManager.GetString("page_left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to דפים פנימיים ימין.
        /// </summary>
        internal static string page_right {
            get {
                return ResourceManager.GetString("page_right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to דפים פנימיים עליון.
        /// </summary>
        internal static string page_top {
            get {
                return ResourceManager.GetString("page_top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שמור.
        /// </summary>
        internal static string SaveAd {
            get {
                return ResourceManager.GetString("SaveAd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to עד תאריך.
        /// </summary>
        internal static string ToDate {
            get {
                return ResourceManager.GetString("ToDate", resourceCulture);
            }
        }
    }
}
