//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Snoopi.web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppUsers {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppUsers() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Snoopi.web.Resources.AppUsers", typeof(AppUsers).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept file.
        /// </summary>
        internal static string AcceptFileButton {
            get {
                return ResourceManager.GetString("AcceptFileButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apartment Number:.
        /// </summary>
        internal static string ApartmentNumber {
            get {
                return ResourceManager.GetString("ApartmentNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password: &lt;sup&gt;(If you want to change it)&lt;/sup&gt;.
        /// </summary>
        internal static string AppUserCurrentPasswordLabel {
            get {
                return ResourceManager.GetString("AppUserCurrentPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please supply a valid email user email address..
        /// </summary>
        internal static string AppUserEmailInvalid {
            get {
                return ResourceManager.GetString("AppUserEmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address: &lt;sup&gt;Used for login&lt;/sup&gt;.
        /// </summary>
        internal static string AppUserEmailLabel {
            get {
                return ResourceManager.GetString("AppUserEmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App user email address is required..
        /// </summary>
        internal static string AppUserEmailRequired {
            get {
                return ResourceManager.GetString("AppUserEmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name:.
        /// </summary>
        internal static string AppUserFirstNameLabel {
            get {
                return ResourceManager.GetString("AppUserFirstNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id Number:.
        /// </summary>
        internal static string AppUserIdNumberLabel {
            get {
                return ResourceManager.GetString("AppUserIdNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Institution:.
        /// </summary>
        internal static string AppUserInstitutionLabel {
            get {
                return ResourceManager.GetString("AppUserInstitutionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name:.
        /// </summary>
        internal static string AppUserLastNameLabel {
            get {
                return ResourceManager.GetString("AppUserLastNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked?.
        /// </summary>
        internal static string AppUserLockedLabel {
            get {
                return ResourceManager.GetString("AppUserLockedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The repeated password does not match the original. Please make sure that your type your password correctly both times..
        /// </summary>
        internal static string AppUserNewPasswordConfirmInvalid {
            get {
                return ResourceManager.GetString("AppUserNewPasswordConfirmInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat the new password: &lt;sup&gt;Please :-)&lt;/sup&gt;.
        /// </summary>
        internal static string AppUserNewPasswordConfirmLabel {
            get {
                return ResourceManager.GetString("AppUserNewPasswordConfirmLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to repeat the password. This is to make sure you typed it right..
        /// </summary>
        internal static string AppUserNewPasswordConfirmRequired {
            get {
                return ResourceManager.GetString("AppUserNewPasswordConfirmRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password:.
        /// </summary>
        internal static string AppUserNewPasswordLabel {
            get {
                return ResourceManager.GetString("AppUserNewPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A password is required for the new app user..
        /// </summary>
        internal static string AppUserNewPasswordRequired {
            get {
                return ResourceManager.GetString("AppUserNewPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone:.
        /// </summary>
        internal static string AppUserPhoneLabel {
            get {
                return ResourceManager.GetString("AppUserPhoneLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total number of app users found:.
        /// </summary>
        internal static string AppUsersCountLabel {
            get {
                return ResourceManager.GetString("AppUsersCountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total number of imported app users:.
        /// </summary>
        internal static string AppUsersImportedCountLabel {
            get {
                return ResourceManager.GetString("AppUsersImportedCountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App users management.
        /// </summary>
        internal static string AppUsersPageTitle {
            get {
                return ResourceManager.GetString("AppUsersPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status:.
        /// </summary>
        internal static string AppUserStatusLabel {
            get {
                return ResourceManager.GetString("AppUserStatusLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total number of app users ready to import:.
        /// </summary>
        internal static string AppUsersToImportCountLabel {
            get {
                return ResourceManager.GetString("AppUsersToImportCountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Study program:.
        /// </summary>
        internal static string AppUserStudyProgramLabel {
            get {
                return ResourceManager.GetString("AppUserStudyProgramLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Study start:.
        /// </summary>
        internal static string AppUserStudyStartLabel {
            get {
                return ResourceManager.GetString("AppUserStudyStartLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth date:.
        /// </summary>
        internal static string BirthDateLabel {
            get {
                return ResourceManager.GetString("BirthDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book data.
        /// </summary>
        internal static string BookData {
            get {
                return ResourceManager.GetString("BookData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interests &amp; hobbies:.
        /// </summary>
        internal static string CategoriesLabel {
            get {
                return ResourceManager.GetString("CategoriesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select at least one interest or hobby!.
        /// </summary>
        internal static string CategoriesRequired {
            get {
                return ResourceManager.GetString("CategoriesRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        internal static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created On.
        /// </summary>
        internal static string CreatedOn {
            get {
                return ResourceManager.GetString("CreatedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete app user!.
        /// </summary>
        internal static string DeleteAppUserButton {
            get {
                return ResourceManager.GetString("DeleteAppUserButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes I am sure..
        /// </summary>
        internal static string DeleteAppUserConfirmCheckbox {
            get {
                return ResourceManager.GetString("DeleteAppUserConfirmCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this app user and all of its data?.
        /// </summary>
        internal static string DeleteAppUserConfirmLabel {
            get {
                return ResourceManager.GetString("DeleteAppUserConfirmLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot delete this app user without confirming that you know what you are doing..
        /// </summary>
        internal static string DeleteAppUserConfirmRequired {
            get {
                return ResourceManager.GetString("DeleteAppUserConfirmRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete app user &lt;i&gt;{0}&lt;/i&gt;.
        /// </summary>
        internal static string DeleteAppUserPageTitle {
            get {
                return ResourceManager.GetString("DeleteAppUserPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete file.
        /// </summary>
        internal static string DeleteFile {
            get {
                return ResourceManager.GetString("DeleteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this institution?.
        /// </summary>
        internal static string DeleteInstitutionConfirm {
            get {
                return ResourceManager.GetString("DeleteInstitutionConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this study program?.
        /// </summary>
        internal static string DeleteStudyProgramConfirm {
            get {
                return ResourceManager.GetString("DeleteStudyProgramConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this study start?.
        /// </summary>
        internal static string DeleteStudyStartConfirm {
            get {
                return ResourceManager.GetString("DeleteStudyStartConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this status?.
        /// </summary>
        internal static string DeleteUserStatusConfirm {
            get {
                return ResourceManager.GetString("DeleteUserStatusConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does not contains.
        /// </summary>
        internal static string DoesNotContains {
            get {
                return ResourceManager.GetString("DoesNotContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit an app user account.
        /// </summary>
        internal static string EditAppUserPageTitle {
            get {
                return ResourceManager.GetString("EditAppUserPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export all to Excel.
        /// </summary>
        internal static string ExportButton {
            get {
                return ResourceManager.GetString("ExportButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export all to Excel for CRM.
        /// </summary>
        internal static string ExportForCRMButton {
            get {
                return ResourceManager.GetString("ExportForCRMButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        internal static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floor:.
        /// </summary>
        internal static string Floor {
            get {
                return ResourceManager.GetString("Floor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id number.
        /// </summary>
        internal static string IdNumber {
            get {
                return ResourceManager.GetString("IdNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import!.
        /// </summary>
        internal static string ImportAppUserButton {
            get {
                return ResourceManager.GetString("ImportAppUserButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import App Users.
        /// </summary>
        internal static string ImportAppUsersPageTitle {
            get {
                return ResourceManager.GetString("ImportAppUsersPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors found in the import file, see details in Comments column..
        /// </summary>
        internal static string ImportErrorsLabel {
            get {
                return ResourceManager.GetString("ImportErrorsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import file format is wrong..
        /// </summary>
        internal static string ImportFileWrongFormat {
            get {
                return ResourceManager.GetString("ImportFileWrongFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No errors found in the import file..
        /// </summary>
        internal static string ImportNoErrorsLabel {
            get {
                return ResourceManager.GetString("ImportNoErrorsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import app user-book relations.
        /// </summary>
        internal static string ImportRelationsPageTitle {
            get {
                return ResourceManager.GetString("ImportRelationsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Institution.
        /// </summary>
        internal static string Institution {
            get {
                return ResourceManager.GetString("Institution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Institution name.
        /// </summary>
        internal static string InstitutionName {
            get {
                return ResourceManager.GetString("InstitutionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Institution name is required!.
        /// </summary>
        internal static string InstitutionNameRequired {
            get {
                return ResourceManager.GetString("InstitutionNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total number of institutions found:.
        /// </summary>
        internal static string InstitutionsCountLabel {
            get {
                return ResourceManager.GetString("InstitutionsCountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Institutions management.
        /// </summary>
        internal static string InstitutionsPageTitle {
            get {
                return ResourceManager.GetString("InstitutionsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsAdv.
        /// </summary>
        internal static string IsAdv {
            get {
                return ResourceManager.GetString("IsAdv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Blocked.
        /// </summary>
        internal static string IsBlocked {
            get {
                return ResourceManager.GetString("IsBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked?.
        /// </summary>
        internal static string IsLocked {
            get {
                return ResourceManager.GetString("IsLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App user email.
        /// </summary>
        internal static string ItemName {
            get {
                return ResourceManager.GetString("ItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last logged in.
        /// </summary>
        internal static string LastLogin {
            get {
                return ResourceManager.GetString("LastLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        internal static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line.
        /// </summary>
        internal static string Line {
            get {
                return ResourceManager.GetString("Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Address.
        /// </summary>
        internal static string MessageAddressInvalid {
            get {
                return ResourceManager.GetString("MessageAddressInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The app user account was created successfully..
        /// </summary>
        internal static string MessageAppUserCreated {
            get {
                return ResourceManager.GetString("MessageAppUserCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The app user account was deleted successfully..
        /// </summary>
        internal static string MessageAppUserDeleted {
            get {
                return ResourceManager.GetString("MessageAppUserDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App user was not found!.
        /// </summary>
        internal static string MessageAppUserNotFound {
            get {
                return ResourceManager.GetString("MessageAppUserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The app user account was saved successfully..
        /// </summary>
        internal static string MessageAppUserSaved {
            get {
                return ResourceManager.GetString("MessageAppUserSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This app user will not be imported..
        /// </summary>
        internal static string MessageAppUserWillNotImported {
            get {
                return ResourceManager.GetString("MessageAppUserWillNotImported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book was not found!.
        /// </summary>
        internal static string MessageBookNotFound {
            get {
                return ResourceManager.GetString("MessageBookNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create app user, this email address is already registered with another app user..
        /// </summary>
        internal static string MessageCreateFailedAlreadyExists {
            get {
                return ResourceManager.GetString("MessageCreateFailedAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create app user, you have supplied an invalid email address..
        /// </summary>
        internal static string MessageCreateFailedEmailAddressInvalid {
            get {
                return ResourceManager.GetString("MessageCreateFailedEmailAddressInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create app user, this Email already exists..
        /// </summary>
        internal static string MessageCreateFailedEmailAlreadyExists {
            get {
                return ResourceManager.GetString("MessageCreateFailedEmailAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create app user, this app user name already exists..
        /// </summary>
        internal static string MessageCreateFailedNameAlreadyExists {
            get {
                return ResourceManager.GetString("MessageCreateFailedNameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create app user, an unknown error occurred..
        /// </summary>
        internal static string MessageCreateFailedUnknown {
            get {
                return ResourceManager.GetString("MessageCreateFailedUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete app user: .
        /// </summary>
        internal static string MessageDeleteFailed {
            get {
                return ResourceManager.GetString("MessageDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email already exists..
        /// </summary>
        internal static string MessageEmailAlreadyExists {
            get {
                return ResourceManager.GetString("MessageEmailAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot change email address. This email address is probably registered with another app user..
        /// </summary>
        internal static string MessageEmailChangeFailed {
            get {
                return ResourceManager.GetString("MessageEmailChangeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select import file!.
        /// </summary>
        internal static string MessageFileNotSelected {
            get {
                return ResourceManager.GetString("MessageFileNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot import app users, an unknown error occurred..
        /// </summary>
        internal static string MessageImportFailedUnknown {
            get {
                return ResourceManager.GetString("MessageImportFailedUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relations import has been successfully completed!.
        /// </summary>
        internal static string MessageImportRelationsSuccess {
            get {
                return ResourceManager.GetString("MessageImportRelationsSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot import relations, an unknown error occurred..
        /// </summary>
        internal static string MessageImportRelationsUnknown {
            get {
                return ResourceManager.GetString("MessageImportRelationsUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App users import has been successfully completed!.
        /// </summary>
        internal static string MessageImportSuccess {
            get {
                return ResourceManager.GetString("MessageImportSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create institution, institution with this name already exists..
        /// </summary>
        internal static string MessageInstitutionCreateFailedNameAlreadyExists {
            get {
                return ResourceManager.GetString("MessageInstitutionCreateFailedNameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete institution that is in use..
        /// </summary>
        internal static string MessageInstitutionDeleteFailedInUse {
            get {
                return ResourceManager.GetString("MessageInstitutionDeleteFailedInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot save institution, institution with this name already exists..
        /// </summary>
        internal static string MessageInstitutionSaveFailedNameAlreadyExists {
            get {
                return ResourceManager.GetString("MessageInstitutionSaveFailedNameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line parsing error.
        /// </summary>
        internal static string MessageLineParsingError {
            get {
                return ResourceManager.GetString("MessageLineParsingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This app user name already exists..
        /// </summary>
        internal static string MessageNameAlreadyExists {
            get {
                return ResourceManager.GetString("MessageNameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No app users found..
        /// </summary>
        internal static string MessageNoAppUsersFound {
            get {
                return ResourceManager.GetString("MessageNoAppUsersFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data here. No app users. Sounds weird? It is. You might want to contact a system administrator, have it checked out....
        /// </summary>
        internal static string MessageNoDataHere {
            get {
                return ResourceManager.GetString("MessageNoDataHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data here. No institutions. Sounds weird? It is. You might want to add a new institution....
        /// </summary>
        internal static string MessageNoDataHereInstitutions {
            get {
                return ResourceManager.GetString("MessageNoDataHereInstitutions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data here. No study programs. Sounds weird? It is. You might want to add a new study program....
        /// </summary>
        internal static string MessageNoDataHereStudyPrograms {
            get {
                return ResourceManager.GetString("MessageNoDataHereStudyPrograms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data here. No study starts. Sounds weird? It is. You might want to add a new study start....
        /// </summary>
        internal static string MessageNoDataHereStudyStarts {
            get {
                return ResourceManager.GetString("MessageNoDataHereStudyStarts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data here. No statuses. Sounds weird? It is. You might want to add a new status....
        /// </summary>
        internal static string MessageNoDataHereUserStatuses {
            get {
                return ResourceManager.GetString("MessageNoDataHereUserStatuses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot change password, the current password do not match the password you supplied..
        /// </summary>
        internal static string MessagePasswordChangeBadOldPassword {
            get {
                return ResourceManager.GetString("MessagePasswordChangeBadOldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot change password, an unknown error has occurred..
        /// </summary>
        internal static string MessagePasswordChangeFailedUnknown {
            get {
                return ResourceManager.GetString("MessagePasswordChangeFailedUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This relation will not be imported..
        /// </summary>
        internal static string MessageRelationWillNotImported {
            get {
                return ResourceManager.GetString("MessageRelationWillNotImported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot save app user, this email already exists..
        /// </summary>
        internal static string MessageSaveFailedEmailAlreadyExists {
            get {
                return ResourceManager.GetString("MessageSaveFailedEmailAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot save app user, this app user name already exists..
        /// </summary>
        internal static string MessageSaveFailedNameAlreadyExists {
            get {
                return ResourceManager.GetString("MessageSaveFailedNameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create study program, study program with this name already exists..
        /// </summary>
        internal static string MessageStudyProgramCreateFailedNameAlreadyExists {
            get {
                return ResourceManager.GetString("MessageStudyProgramCreateFailedNameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete study program that is in use..
        /// </summary>
        internal static string MessageStudyProgramDeleteFailedInUse {
            get {
                return ResourceManager.GetString("MessageStudyProgramDeleteFailedInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot save study program, study program with this name already exists..
        /// </summary>
        internal static string MessageStudyProgramSaveFailedNameAlreadyExists {
            get {
                return ResourceManager.GetString("MessageStudyProgramSaveFailedNameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create study start, study start with this name already exists..
        /// </summary>
        internal static string MessageStudyStartCreateFailedNameAlreadyExists {
            get {
                return ResourceManager.GetString("MessageStudyStartCreateFailedNameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete study start that is in use..
        /// </summary>
        internal static string MessageStudyStartDeleteFailedInUse {
            get {
                return ResourceManager.GetString("MessageStudyStartDeleteFailedInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot save study start, study start with this name already exists..
        /// </summary>
        internal static string MessageStudyStartSaveFailedNameAlreadyExists {
            get {
                return ResourceManager.GetString("MessageStudyStartSaveFailedNameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot update app users display order, an unknown error occurred..
        /// </summary>
        internal static string MessageUpdateOrderError {
            get {
                return ResourceManager.GetString("MessageUpdateOrderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App users display order has been successfully updated!.
        /// </summary>
        internal static string MessageUpdateOrderSuccess {
            get {
                return ResourceManager.GetString("MessageUpdateOrderSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create status, status with this name already exists..
        /// </summary>
        internal static string MessageUserStatusCreateFailedNameAlreadyExists {
            get {
                return ResourceManager.GetString("MessageUserStatusCreateFailedNameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete user status that is in use..
        /// </summary>
        internal static string MessageUserStatusDeleteFailedInUse {
            get {
                return ResourceManager.GetString("MessageUserStatusDeleteFailedInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot save status, status with this name already exists..
        /// </summary>
        internal static string MessageUserStatusSaveFailedNameAlreadyExists {
            get {
                return ResourceManager.GetString("MessageUserStatusSaveFailedNameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New app user.
        /// </summary>
        internal static string NewAppUserButton {
            get {
                return ResourceManager.GetString("NewAppUserButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new app user account.
        /// </summary>
        internal static string NewAppUserPageTitle {
            get {
                return ResourceManager.GetString("NewAppUserPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App users display order management.
        /// </summary>
        internal static string OrderPageTitle {
            get {
                return ResourceManager.GetString("OrderPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile image.
        /// </summary>
        internal static string ProfileImage {
            get {
                return ResourceManager.GetString("ProfileImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile image:.
        /// </summary>
        internal static string ProfileImageLabel {
            get {
                return ResourceManager.GetString("ProfileImageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total number of relations found:.
        /// </summary>
        internal static string RelationsCountLabel {
            get {
                return ResourceManager.GetString("RelationsCountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total number of imported relations:.
        /// </summary>
        internal static string RelationsImportedCountLabel {
            get {
                return ResourceManager.GetString("RelationsImportedCountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total number of relations ready to import:.
        /// </summary>
        internal static string RelationsToImportCountLabel {
            get {
                return ResourceManager.GetString("RelationsToImportCountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save app user.
        /// </summary>
        internal static string SaveButton {
            get {
                return ResourceManager.GetString("SaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string SearchButton {
            get {
                return ResourceManager.GetString("SearchButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search app users:.
        /// </summary>
        internal static string SearchLabel {
            get {
                return ResourceManager.GetString("SearchLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select import file:.
        /// </summary>
        internal static string SelectImportFileLabel {
            get {
                return ResourceManager.GetString("SelectImportFileLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show study data?.
        /// </summary>
        internal static string ShowStudyData {
            get {
                return ResourceManager.GetString("ShowStudyData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Study program.
        /// </summary>
        internal static string StudyProgram {
            get {
                return ResourceManager.GetString("StudyProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Study program name.
        /// </summary>
        internal static string StudyProgramName {
            get {
                return ResourceManager.GetString("StudyProgramName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Study program name is required!.
        /// </summary>
        internal static string StudyProgramNameRequired {
            get {
                return ResourceManager.GetString("StudyProgramNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total number of study programs found:.
        /// </summary>
        internal static string StudyProgramsCountLabel {
            get {
                return ResourceManager.GetString("StudyProgramsCountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Study programs management.
        /// </summary>
        internal static string StudyProgramsPageTitle {
            get {
                return ResourceManager.GetString("StudyProgramsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Study start.
        /// </summary>
        internal static string StudyStart {
            get {
                return ResourceManager.GetString("StudyStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Study start.
        /// </summary>
        internal static string StudyStartName {
            get {
                return ResourceManager.GetString("StudyStartName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Study start name is required!.
        /// </summary>
        internal static string StudyStartNameRequired {
            get {
                return ResourceManager.GetString("StudyStartNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total number of study starts found:.
        /// </summary>
        internal static string StudyStartsCountLabel {
            get {
                return ResourceManager.GetString("StudyStartsCountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Study starts management.
        /// </summary>
        internal static string StudyStartsPageTitle {
            get {
                return ResourceManager.GetString("StudyStartsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update display order!.
        /// </summary>
        internal static string UpdateOrderButton {
            get {
                return ResourceManager.GetString("UpdateOrderButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total number of statuses found:.
        /// </summary>
        internal static string UserStatusesCountLabel {
            get {
                return ResourceManager.GetString("UserStatusesCountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User statuses management.
        /// </summary>
        internal static string UserStatusesPageTitle {
            get {
                return ResourceManager.GetString("UserStatusesPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status name.
        /// </summary>
        internal static string UserStatusName {
            get {
                return ResourceManager.GetString("UserStatusName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status name is required!.
        /// </summary>
        internal static string UserStatusNameRequired {
            get {
                return ResourceManager.GetString("UserStatusNameRequired", resourceCulture);
            }
        }
    }
}
