//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Snoopi.web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Bid {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Bid() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Snoopi.web.Resources.Bid", typeof(Bid).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אפליקציה.
        /// </summary>
        internal static string Application {
            get {
                return ResourceManager.GetString("Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אושרה ע&quot;י ספק.
        /// </summary>
        internal static string ApprovedBySupplier {
            get {
                return ResourceManager.GetString("ApprovedBySupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to חזרה לעסקאות מנהל.
        /// </summary>
        internal static string BackToAdminBids {
            get {
                return ResourceManager.GetString("BackToAdminBids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מספר מכרז.
        /// </summary>
        internal static string BidId {
            get {
                return ResourceManager.GetString("BidId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מספר מכרז: .
        /// </summary>
        internal static string BidNumber {
            get {
                return ResourceManager.GetString("BidNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bids.
        /// </summary>
        internal static string BidsPageTitle {
            get {
                return ResourceManager.GetString("BidsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ביטול מכרז.
        /// </summary>
        internal static string CancelBid {
            get {
                return ResourceManager.GetString("CancelBid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to עיר.
        /// </summary>
        internal static string CityName {
            get {
                return ResourceManager.GetString("CityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to חיפוש לפי עיר:.
        /// </summary>
        internal static string CitySearch {
            get {
                return ResourceManager.GetString("CitySearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לקוח אישר קבלה.
        /// </summary>
        internal static string CustomerApprovedSupplied {
            get {
                return ResourceManager.GetString("CustomerApprovedSupplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מספר לקוח.
        /// </summary>
        internal static string CustomerId {
            get {
                return ResourceManager.GetString("CustomerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שם לקוח.
        /// </summary>
        internal static string CustomerName {
            get {
                return ResourceManager.GetString("CustomerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details - .
        /// </summary>
        internal static string CustomersPageTitle {
            get {
                return ResourceManager.GetString("CustomersPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Temp.
        /// </summary>
        internal static string CustomersTempPageTitle {
            get {
                return ResourceManager.GetString("CustomersTempPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Bid.
        /// </summary>
        internal static string DeleteBid {
            get {
                return ResourceManager.GetString("DeleteBid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error when trying to delete bid.
        /// </summary>
        internal static string DeleteBidError {
            get {
                return ResourceManager.GetString("DeleteBidError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting bid has been successful.
        /// </summary>
        internal static string DeleteBidSuccess {
            get {
                return ResourceManager.GetString("DeleteBidSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מכרזים פעילים.
        /// </summary>
        internal static string DetailsMyActiveBidsPageTitle {
            get {
                return ResourceManager.GetString("DetailsMyActiveBidsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מכרזים שננטשו עם הצעות.
        /// </summary>
        internal static string DetailsMyBidsAbandonedPageTitle {
            get {
                return ResourceManager.GetString("DetailsMyBidsAbandonedPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מכרזים שנרכשו.
        /// </summary>
        internal static string DetailsMyBidsPurchasePageTitle {
            get {
                return ResourceManager.GetString("DetailsMyBidsPurchasePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to פירוט מרכזים .
        /// </summary>
        internal static string DetailsMyCountBidsPageTitle {
            get {
                return ResourceManager.GetString("DetailsMyCountBidsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מכרזים ללא הצעות.
        /// </summary>
        internal static string DetailsMyWithNotOffersPageTitle {
            get {
                return ResourceManager.GetString("DetailsMyWithNotOffersPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ת. סיום מכרז.
        /// </summary>
        internal static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אין אפשרות לבטל מכרז ,אירעה שגיאה או שההזמנה אושרה כבר ע&quot;י ספק.
        /// </summary>
        internal static string ErrorCancelBid {
            get {
                return ResourceManager.GetString("ErrorCancelBid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to יצוא לאקסל.
        /// </summary>
        internal static string ExportButton {
            get {
                return ResourceManager.GetString("ExportButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מתאריך:.
        /// </summary>
        internal static string FromDate {
            get {
                return ResourceManager.GetString("FromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gift.
        /// </summary>
        internal static string Gift {
            get {
                return ResourceManager.GetString("Gift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to האם פעיל?.
        /// </summary>
        internal static string IsActive {
            get {
                return ResourceManager.GetString("IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Order.
        /// </summary>
        internal static string IsOrder {
            get {
                return ResourceManager.GetString("IsOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Bids Found.
        /// </summary>
        internal static string MessageNoBidsFound {
            get {
                return ResourceManager.GetString("MessageNoBidsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Bids.
        /// </summary>
        internal static string MyActiveBidsPageTitle {
            get {
                return ResourceManager.GetString("MyActiveBidsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bids Abandoned.
        /// </summary>
        internal static string MyBidsAbandonedPageTitle {
            get {
                return ResourceManager.GetString("MyBidsAbandonedPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bids Purchase.
        /// </summary>
        internal static string MyBidsPurchasePageTitle {
            get {
                return ResourceManager.GetString("MyBidsPurchasePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count Bids.
        /// </summary>
        internal static string MyCountBidsPageTitle {
            get {
                return ResourceManager.GetString("MyCountBidsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Auto Refresh.
        /// </summary>
        internal static string NoAutoRefresh {
            get {
                return ResourceManager.GetString("NoAutoRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מספר הצעות.
        /// </summary>
        internal static string OffersCount {
            get {
                return ResourceManager.GetString("OffersCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details to Bid num.
        /// </summary>
        internal static string OffersTitle {
            get {
                return ResourceManager.GetString("OffersTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Date.
        /// </summary>
        internal static string OrderDate {
            get {
                return ResourceManager.GetString("OrderDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to סטטוס הזמנה.
        /// </summary>
        internal static string OrderStatus {
            get {
                return ResourceManager.GetString("OrderStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to טלפון.
        /// </summary>
        internal static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מחיר.
        /// </summary>
        internal static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מוצרים.
        /// </summary>
        internal static string Products {
            get {
                return ResourceManager.GetString("Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שגר לספק.
        /// </summary>
        internal static string ResendDeal {
            get {
                return ResourceManager.GetString("ResendDeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שיגור העסקה נכשל.
        /// </summary>
        internal static string ResendDealFail {
            get {
                return ResourceManager.GetString("ResendDealFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to העסקה שוגרה לספק &quot;XXX&quot; בהצלחה.
        /// </summary>
        internal static string ResendDealSucceed {
            get {
                return ResourceManager.GetString("ResendDealSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שיגור עסקה לספק.
        /// </summary>
        internal static string ResendDealTitle {
            get {
                return ResourceManager.GetString("ResendDealTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to חפש.
        /// </summary>
        internal static string SearchButton {
            get {
                return ResourceManager.GetString("SearchButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to חיפוש מתקדם:.
        /// </summary>
        internal static string SearchBy {
            get {
                return ResourceManager.GetString("SearchBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to טלפון של לקוח:.
        /// </summary>
        internal static string SearchPhone {
            get {
                return ResourceManager.GetString("SearchPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מספר סידורי של לקוח:.
        /// </summary>
        internal static string SerchCustomerId {
            get {
                return ResourceManager.GetString("SerchCustomerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מקור.
        /// </summary>
        internal static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ת. תחילת מכרז.
        /// </summary>
        internal static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מכרז בוטל בהצלחה.
        /// </summary>
        internal static string SuccessCancelBid {
            get {
                return ResourceManager.GetString("SuccessCancelBid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum Abandoned Bids:.
        /// </summary>
        internal static string SumAbandonedBids {
            get {
                return ResourceManager.GetString("SumAbandonedBids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum Active Bids:.
        /// </summary>
        internal static string SumActiveBids {
            get {
                return ResourceManager.GetString("SumActiveBids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum Count Bids:.
        /// </summary>
        internal static string SumCountBids {
            get {
                return ResourceManager.GetString("SumCountBids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum Purchase Bids: .
        /// </summary>
        internal static string SumPurchaseBids {
            get {
                return ResourceManager.GetString("SumPurchaseBids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to נשלחה ללקוח ב: XXX.
        /// </summary>
        internal static string SuppliedToTheCustomer {
            get {
                return ResourceManager.GetString("SuppliedToTheCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum Supplier:.
        /// </summary>
        internal static string SupplierCountLabel {
            get {
                return ResourceManager.GetString("SupplierCountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שם ספק.
        /// </summary>
        internal static string SupplierName {
            get {
                return ResourceManager.GetString("SupplierName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temp.
        /// </summary>
        internal static string Temp {
            get {
                return ResourceManager.GetString("Temp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to פירוט מספר מכרזים פעילים .
        /// </summary>
        internal static string TitleGlobalSupplierBidsActive {
            get {
                return ResourceManager.GetString("TitleGlobalSupplierBidsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to פירוט מספר הצעות שלא זכה .
        /// </summary>
        internal static string TitleGlobalSupplierBidsNoWin {
            get {
                return ResourceManager.GetString("TitleGlobalSupplierBidsNoWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to פירוט מספר הצעות .
        /// </summary>
        internal static string TitleGlobalSupplierBidsOffers {
            get {
                return ResourceManager.GetString("TitleGlobalSupplierBidsOffers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to פירוט מספר זכיות .
        /// </summary>
        internal static string TitleGlobalSupplierBidsWin {
            get {
                return ResourceManager.GetString("TitleGlobalSupplierBidsWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to עד תאריך:.
        /// </summary>
        internal static string ToDate {
            get {
                return ResourceManager.GetString("ToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אתר.
        /// </summary>
        internal static string WebSite {
            get {
                return ResourceManager.GetString("WebSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
