//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Snoopi.web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DatabaseBackup {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DatabaseBackup() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Snoopi.web.Resources.DatabaseBackup", typeof(DatabaseBackup).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to perform a database restore?.
        /// </summary>
        internal static string AcceptRestore1ErrorMessage {
            get {
                return ResourceManager.GetString("AcceptRestore1ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you aware that restoring from the wrong file can leave the system in an unstabe state?.
        /// </summary>
        internal static string AcceptRestore2ErrorMessage {
            get {
                return ResourceManager.GetString("AcceptRestore2ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I really want to restore the database from this file..
        /// </summary>
        internal static string AcceptRestoreCheckbox1 {
            get {
                return ResourceManager.GetString("AcceptRestoreCheckbox1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am aware that restoring from the wrong file can leave the system in an unstabe state..
        /// </summary>
        internal static string AcceptRestoreCheckbox2 {
            get {
                return ResourceManager.GetString("AcceptRestoreCheckbox2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The uploaded file is empty. In order to perform a database restore, you need to choose an actual backup file..
        /// </summary>
        internal static string BackupFileEmptyErrorMessage {
            get {
                return ResourceManager.GetString("BackupFileEmptyErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup file:.
        /// </summary>
        internal static string BackupFileLabel {
            get {
                return ResourceManager.GetString("BackupFileLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to choose a file..
        /// </summary>
        internal static string BackupFileRequiredErrorMessage {
            get {
                return ResourceManager.GetString("BackupFileRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (.SQL or .GZ).
        /// </summary>
        internal static string BackupFileType {
            get {
                return ResourceManager.GetString("BackupFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file must be a .SQL or .GZ file..
        /// </summary>
        internal static string BackupFileTypeErrorMessage {
            get {
                return ResourceManager.GetString("BackupFileTypeErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database backup and restore.
        /// </summary>
        internal static string BackupPageTitle {
            get {
                return ResourceManager.GetString("BackupPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup.
        /// </summary>
        internal static string BackupPanelTitle {
            get {
                return ResourceManager.GetString("BackupPanelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compress backup file with GZip.
        /// </summary>
        internal static string BackupToGzip {
            get {
                return ResourceManager.GetString("BackupToGzip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download a full database backup.
        /// </summary>
        internal static string DownloadBackupButton {
            get {
                return ResourceManager.GetString("DownloadBackupButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perform restore.
        /// </summary>
        internal static string RestoreButton {
            get {
                return ResourceManager.GetString("RestoreButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The restore process is done. Please ensure that all is well..
        /// </summary>
        internal static string RestoreFinishedMessage {
            get {
                return ResourceManager.GetString("RestoreFinishedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The restore process was unsuccessful. An error occurred: 
        ///{0}.
        /// </summary>
        internal static string RestoreGeneralError {
            get {
                return ResourceManager.GetString("RestoreGeneralError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        internal static string RestorePanelTitle {
            get {
                return ResourceManager.GetString("RestorePanelTitle", resourceCulture);
            }
        }
    }
}
