//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Snoopi.web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Snoopi.web.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve.
        /// </summary>
        internal static string Approve {
            get {
                return ResourceManager.GetString("Approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved.
        /// </summary>
        internal static string Approved {
            get {
                return ResourceManager.GetString("Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Date.
        /// </summary>
        internal static string CreateDate {
            get {
                return ResourceManager.GetString("CreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete File.
        /// </summary>
        internal static string DeleteFile {
            get {
                return ResourceManager.GetString("DeleteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Message!.
        /// </summary>
        internal static string DeleteMessageButton {
            get {
                return ResourceManager.GetString("DeleteMessageButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes I am sure..
        /// </summary>
        internal static string DeleteMessageConfirmCheckbox {
            get {
                return ResourceManager.GetString("DeleteMessageConfirmCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this Message and all of its data?.
        /// </summary>
        internal static string DeleteMessageConfirmLabel {
            get {
                return ResourceManager.GetString("DeleteMessageConfirmLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot delete this Message without confirming that you know what you are doing..
        /// </summary>
        internal static string DeleteMessageConfirmRequired {
            get {
                return ResourceManager.GetString("DeleteMessageConfirmRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Message &lt;i&gt;{0}&lt;/i&gt;.
        /// </summary>
        internal static string DeleteMessagePageTitle {
            get {
                return ResourceManager.GetString("DeleteMessagePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Message.
        /// </summary>
        internal static string DeleteMessagesPageTitle {
            get {
                return ResourceManager.GetString("DeleteMessagesPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit a Message account.
        /// </summary>
        internal static string EditMessagePageTitle {
            get {
                return ResourceManager.GetString("EditMessagePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image File Wrong Format.
        /// </summary>
        internal static string ImageFileWrongFormat {
            get {
                return ResourceManager.GetString("ImageFileWrongFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images.
        /// </summary>
        internal static string Images {
            get {
                return ResourceManager.GetString("Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image 1.
        /// </summary>
        internal static string Img1 {
            get {
                return ResourceManager.GetString("Img1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image 2.
        /// </summary>
        internal static string Img2 {
            get {
                return ResourceManager.GetString("Img2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image 3.
        /// </summary>
        internal static string Img3 {
            get {
                return ResourceManager.GetString("Img3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked?.
        /// </summary>
        internal static string IsLocked {
            get {
                return ResourceManager.GetString("IsLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last logged in.
        /// </summary>
        internal static string LastLogin {
            get {
                return ResourceManager.GetString("LastLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coor Y.
        /// </summary>
        internal static string Latitude {
            get {
                return ResourceManager.GetString("Latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coor X.
        /// </summary>
        internal static string Longitude {
            get {
                return ResourceManager.GetString("Longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address:.
        /// </summary>
        internal static string MessageAddressLabel {
            get {
                return ResourceManager.GetString("MessageAddressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area:.
        /// </summary>
        internal static string MessageAreaLabel {
            get {
                return ResourceManager.GetString("MessageAreaLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coordi:.
        /// </summary>
        internal static string MessageCorLabel {
            get {
                return ResourceManager.GetString("MessageCorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create Message, this email address is already registered with another Message..
        /// </summary>
        internal static string MessageCreateFailedAlreadyExists {
            get {
                return ResourceManager.GetString("MessageCreateFailedAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create Message, you have supplied an invalid email address..
        /// </summary>
        internal static string MessageCreateFailedEmailAddressInvalid {
            get {
                return ResourceManager.GetString("MessageCreateFailedEmailAddressInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create Message, an unknown error occurred..
        /// </summary>
        internal static string MessageCreateFailedUnknown {
            get {
                return ResourceManager.GetString("MessageCreateFailedUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password: &lt;sup&gt;(If you want to change it)&lt;/sup&gt;.
        /// </summary>
        internal static string MessageCurrentPasswordLabel {
            get {
                return ResourceManager.GetString("MessageCurrentPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message content :.
        /// </summary>
        internal static string MessageDescriptionLabel {
            get {
                return ResourceManager.GetString("MessageDescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot change email address. This email address is probably registered with another Message..
        /// </summary>
        internal static string MessageEmailChangeFailed {
            get {
                return ResourceManager.GetString("MessageEmailChangeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please supply a valid email Message email address..
        /// </summary>
        internal static string MessageEmailInvalid {
            get {
                return ResourceManager.GetString("MessageEmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address: &lt;sup&gt;Used for login&lt;/sup&gt;.
        /// </summary>
        internal static string MessageEmailLabel {
            get {
                return ResourceManager.GetString("MessageEmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message email address is required..
        /// </summary>
        internal static string MessageEmailRequired {
            get {
                return ResourceManager.GetString("MessageEmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature:.
        /// </summary>
        internal static string MessageFeatureLabel {
            get {
                return ResourceManager.GetString("MessageFeatureLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Id.
        /// </summary>
        internal static string MessageId {
            get {
                return ResourceManager.GetString("MessageId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y:.
        /// </summary>
        internal static string MessageLatitudeLabel {
            get {
                return ResourceManager.GetString("MessageLatitudeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked?.
        /// </summary>
        internal static string MessageLockedLabel {
            get {
                return ResourceManager.GetString("MessageLockedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X:.
        /// </summary>
        internal static string MessageLongitudeLabel {
            get {
                return ResourceManager.GetString("MessageLongitudeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Message account was created and sended successfully..
        /// </summary>
        internal static string MessageMessageCreated {
            get {
                return ResourceManager.GetString("MessageMessageCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Deleted.
        /// </summary>
        internal static string MessageMessageDeleted {
            get {
                return ResourceManager.GetString("MessageMessageDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Message account was saved successfully..
        /// </summary>
        internal static string MessageMessageSaved {
            get {
                return ResourceManager.GetString("MessageMessageSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Name:.
        /// </summary>
        internal static string MessageNameLabel {
            get {
                return ResourceManager.GetString("MessageNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The repeated password does not match the original. Please make sure that your type your password correctly both times..
        /// </summary>
        internal static string MessageNewPasswordConfirmInvalid {
            get {
                return ResourceManager.GetString("MessageNewPasswordConfirmInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat the new password: &lt;sup&gt;Please :-)&lt;/sup&gt;.
        /// </summary>
        internal static string MessageNewPasswordConfirmLabel {
            get {
                return ResourceManager.GetString("MessageNewPasswordConfirmLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to repeat the password. This is to make sure you typed it right..
        /// </summary>
        internal static string MessageNewPasswordConfirmRequired {
            get {
                return ResourceManager.GetString("MessageNewPasswordConfirmRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password:.
        /// </summary>
        internal static string MessageNewPasswordLabel {
            get {
                return ResourceManager.GetString("MessageNewPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A password is required for the new Message..
        /// </summary>
        internal static string MessageNewPasswordRequired {
            get {
                return ResourceManager.GetString("MessageNewPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data here. No Messages. Sounds weird? It is. You might want to contact a system administrator, have it checked out....
        /// </summary>
        internal static string MessageNoDataHere {
            get {
                return ResourceManager.GetString("MessageNoDataHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Messages found..
        /// </summary>
        internal static string MessageNoMessagesFound {
            get {
                return ResourceManager.GetString("MessageNoMessagesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening Hours:.
        /// </summary>
        internal static string MessageOpeningHoursLabel {
            get {
                return ResourceManager.GetString("MessageOpeningHoursLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot change password, the current password do not match the password you supplied..
        /// </summary>
        internal static string MessagePasswordChangeBadOldPassword {
            get {
                return ResourceManager.GetString("MessagePasswordChangeBadOldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot change password, an unknown error has occurred..
        /// </summary>
        internal static string MessagePasswordChangeFailedUnknown {
            get {
                return ResourceManager.GetString("MessagePasswordChangeFailedUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price:.
        /// </summary>
        internal static string MessagePriceLabel {
            get {
                return ResourceManager.GetString("MessagePriceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recomended: .
        /// </summary>
        internal static string MessageRecomendedLabel {
            get {
                return ResourceManager.GetString("MessageRecomendedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total number of Messages found:.
        /// </summary>
        internal static string MessagesCountLabel {
            get {
                return ResourceManager.GetString("MessagesCountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Season:.
        /// </summary>
        internal static string MessageSeasonLabel {
            get {
                return ResourceManager.GetString("MessageSeasonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site:.
        /// </summary>
        internal static string MessageSiteLabel {
            get {
                return ResourceManager.GetString("MessageSiteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages management.
        /// </summary>
        internal static string MessagesPageTitle {
            get {
                return ResourceManager.GetString("MessagesPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Area:.
        /// </summary>
        internal static string MessageSubAreaLabel {
            get {
                return ResourceManager.GetString("MessageSubAreaLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tips: .
        /// </summary>
        internal static string MessageTipsLabel {
            get {
                return ResourceManager.GetString("MessageTipsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type:.
        /// </summary>
        internal static string MessageTypeLabel {
            get {
                return ResourceManager.GetString("MessageTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Message.
        /// </summary>
        internal static string NewMessageButton {
            get {
                return ResourceManager.GetString("NewMessageButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new Message account.
        /// </summary>
        internal static string NewMessagePageTitle {
            get {
                return ResourceManager.GetString("NewMessagePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening Hours.
        /// </summary>
        internal static string OpeningHours {
            get {
                return ResourceManager.GetString("OpeningHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage database backup and restores.
        /// </summary>
        internal static string Perm_sys_backups {
            get {
                return ResourceManager.GetString("Perm_sys_backups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage app Messages.
        /// </summary>
        internal static string Perm_sys_edit_appusers {
            get {
                return ResourceManager.GetString("Perm_sys_edit_appusers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage email templates and logs.
        /// </summary>
        internal static string Perm_sys_edit_emails {
            get {
                return ResourceManager.GetString("Perm_sys_edit_emails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Messages.
        /// </summary>
        internal static string Perm_sys_edit_users {
            get {
                return ResourceManager.GetString("Perm_sys_edit_users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage system settings.
        /// </summary>
        internal static string Perm_sys_settings {
            get {
                return ResourceManager.GetString("Perm_sys_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View app Messages.
        /// </summary>
        internal static string Perm_sys_view_appusers {
            get {
                return ResourceManager.GetString("Perm_sys_view_appusers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View email templates and logs.
        /// </summary>
        internal static string Perm_sys_view_emails {
            get {
                return ResourceManager.GetString("Perm_sys_view_emails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Messages.
        /// </summary>
        internal static string Perm_sys_view_users {
            get {
                return ResourceManager.GetString("Perm_sys_view_users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissions.
        /// </summary>
        internal static string PermissionsPanel {
            get {
                return ResourceManager.GetString("PermissionsPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recomended.
        /// </summary>
        internal static string Recomended {
            get {
                return ResourceManager.GetString("Recomended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Message.
        /// </summary>
        internal static string SaveButton {
            get {
                return ResourceManager.GetString("SaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Messages:.
        /// </summary>
        internal static string SearchLabel {
            get {
                return ResourceManager.GetString("SearchLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        internal static string SendButton {
            get {
                return ResourceManager.GetString("SendButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending Date.
        /// </summary>
        internal static string SendingDate {
            get {
                return ResourceManager.GetString("SendingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending Date:.
        /// </summary>
        internal static string SendingDateLabel_ {
            get {
                return ResourceManager.GetString("SendingDateLabel:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site.
        /// </summary>
        internal static string Site {
            get {
                return ResourceManager.GetString("Site", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Area.
        /// </summary>
        internal static string SubArea {
            get {
                return ResourceManager.GetString("SubArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
