//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Snoopi.web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PromotedArea {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PromotedArea() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Snoopi.web.Resources.PromotedArea", typeof(PromotedArea).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to קוד אשכול.
        /// </summary>
        internal static string AreaId {
            get {
                return ResourceManager.GetString("AreaId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שם אשכול.
        /// </summary>
        internal static string AreaName {
            get {
                return ResourceManager.GetString("AreaName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to חתול - הכי נמכרים.
        /// </summary>
        internal static string cat_most_popular {
            get {
                return ResourceManager.GetString("cat_most_popular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to חתול - הכי משתלם.
        /// </summary>
        internal static string cat_most_profitable {
            get {
                return ResourceManager.GetString("cat_most_profitable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to האם אתה בטוח שברצונך להסיר את הספק מרשימת המקודמים?.
        /// </summary>
        internal static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to כלב - הכי נמכרים.
        /// </summary>
        internal static string dog_most_popular {
            get {
                return ResourceManager.GetString("dog_most_popular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to כלב - הכי משתלם.
        /// </summary>
        internal static string dog_most_profitable {
            get {
                return ResourceManager.GetString("dog_most_profitable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ערוך.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מתאריך.
        /// </summary>
        internal static string FromDate {
            get {
                return ResourceManager.GetString("FromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לא נימצאו נתונים.
        /// </summary>
        internal static string NoItems {
            get {
                return ResourceManager.GetString("NoItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לא נבחר.
        /// </summary>
        internal static string NoSelection {
            get {
                return ResourceManager.GetString("NoSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ניהול מוצרים מקודמים.
        /// </summary>
        internal static string ProductPromotedAreaHeader {
            get {
                return ResourceManager.GetString("ProductPromotedAreaHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הסר.
        /// </summary>
        internal static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שמור.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to קדימות.
        /// </summary>
        internal static string Section {
            get {
                return ResourceManager.GetString("Section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ניהול ספקים מקודמים.
        /// </summary>
        internal static string SuplierPromotedAreaHeader {
            get {
                return ResourceManager.GetString("SuplierPromotedAreaHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to עד תאריך.
        /// </summary>
        internal static string ToDate {
            get {
                return ResourceManager.GetString("ToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to משקל.
        /// </summary>
        internal static string Weight {
            get {
                return ResourceManager.GetString("Weight", resourceCulture);
            }
        }
    }
}
