//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Snoopi.web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PushResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PushResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Snoopi.web.Resources.PushResource", typeof(PushResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to דירה.
        /// </summary>
        internal static string ApartmentNumber {
            get {
                return ResourceManager.GetString("ApartmentNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to קומה.
        /// </summary>
        internal static string Floor {
            get {
                return ResourceManager.GetString("Floor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לא נמצאו הצעות מתאימות.
        /// </summary>
        internal static string NoPushOfferText {
            get {
                return ResourceManager.GetString("NoPushOfferText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to נמצאו {0} הצעות מתאימות.
        /// </summary>
        internal static string PushOfferText {
            get {
                return ResourceManager.GetString("PushOfferText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מודעת האימוץ התקבלה.
        /// </summary>
        internal static string PushYad2Accepted {
            get {
                return ResourceManager.GetString("PushYad2Accepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מודעת האימוץ נדחתה.
        /// </summary>
        internal static string PushYad2Deny {
            get {
                return ResourceManager.GetString("PushYad2Deny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to דירוג ספק.
        /// </summary>
        internal static string RateSupplier {
            get {
                return ResourceManager.GetString("RateSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to נא אשר קבלת מוצרים.
        /// </summary>
        internal static string ReceivedOrder {
            get {
                return ResourceManager.GetString("ReceivedOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to רחוב.
        /// </summary>
        internal static string Street {
            get {
                return ResourceManager.GetString("Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to העסקה אושרה בדוק את הפרטים.
        /// </summary>
        internal static string SupplierApproved {
            get {
                return ResourceManager.GetString("SupplierApproved", resourceCulture);
            }
        }
    }
}
