//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Snoopi.web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SystemSettings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SystemSettings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Snoopi.web.Resources.SystemSettings", typeof(SystemSettings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin email address:.
        /// </summary>
        internal static string AdminEmailLabel {
            get {
                return ResourceManager.GetString("AdminEmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App users&apos; upload local folder (From API layer POV):.
        /// </summary>
        internal static string ApiAppUsersUploadFolderLabel {
            get {
                return ResourceManager.GetString("ApiAppUsersUploadFolderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Api root url:.
        /// </summary>
        internal static string ApiRootUrlLabel {
            get {
                return ResourceManager.GetString("ApiRootUrlLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporary uploads local folder (From API layer POV):.
        /// </summary>
        internal static string ApiTempUploadFolderLabel {
            get {
                return ResourceManager.GetString("ApiTempUploadFolderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App-users settings.
        /// </summary>
        internal static string AppUserSettingsPanel {
            get {
                return ResourceManager.GetString("AppUserSettingsPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App users&apos; upload local folder:.
        /// </summary>
        internal static string AppUsersUploadFolderLabel {
            get {
                return ResourceManager.GetString("AppUsersUploadFolderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do app users needs to verify their email address?.
        /// </summary>
        internal static string AppUserVerifyEmailLabel {
            get {
                return ResourceManager.GetString("AppUserVerifyEmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default &quot;from&quot; email address:.
        /// </summary>
        internal static string DefaultEmailFromLabel {
            get {
                return ResourceManager.GetString("DefaultEmailFromLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default &quot;from&quot; email name:.
        /// </summary>
        internal static string DefaultEmailFromNameLabel {
            get {
                return ResourceManager.GetString("DefaultEmailFromNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default &quot;reply-to&quot; email address:.
        /// </summary>
        internal static string DefaultEmailReplyToLabel {
            get {
                return ResourceManager.GetString("DefaultEmailReplyToLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default &quot;reply-to&quot; email name:.
        /// </summary>
        internal static string DefaultEmailReplyToNameLabel {
            get {
                return ResourceManager.GetString("DefaultEmailReplyToNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage system settings.
        /// </summary>
        internal static string EditSettingsPageTitle {
            get {
                return ResourceManager.GetString("EditSettingsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When an account is approved, and a notification email:.
        /// </summary>
        internal static string EmailTemplateAccountApprovedLabel {
            get {
                return ResourceManager.GetString("EmailTemplateAccountApprovedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When an app user wants to reset password, send the reset link in email:.
        /// </summary>
        internal static string EmailTemplateAppUserForgotPasswordLabel {
            get {
                return ResourceManager.GetString("EmailTemplateAppUserForgotPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When new account is created in approved status, send a login details:.
        /// </summary>
        internal static string EmailTemplateNewAccountLoginDetailsApprovedLabel {
            get {
                return ResourceManager.GetString("EmailTemplateNewAccountLoginDetailsApprovedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When new account is created in unapproved status, send a login details:.
        /// </summary>
        internal static string EmailTemplateNewAccountLoginDetailsNotYetApprovedLabel {
            get {
                return ResourceManager.GetString("EmailTemplateNewAccountLoginDetailsNotYetApprovedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When new account is created in approved status, send a welcome email:.
        /// </summary>
        internal static string EmailTemplateNewAccountWelcomeApprovedLabel {
            get {
                return ResourceManager.GetString("EmailTemplateNewAccountWelcomeApprovedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When new account is created in unapproved status, send a welcome email:.
        /// </summary>
        internal static string EmailTemplateNewAccountWelcomeNotYetApprovedLabel {
            get {
                return ResourceManager.GetString("EmailTemplateNewAccountWelcomeNotYetApprovedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When a new app user signs up, and does not need verification, send a welcome email:.
        /// </summary>
        internal static string EmailTemplateNewAppUserWelcomeLabel {
            get {
                return ResourceManager.GetString("EmailTemplateNewAppUserWelcomeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When a new app user signs up, and needs verification, send a welcome email:.
        /// </summary>
        internal static string EmailTemplateNewAppUserWelcomeVerifyEmailLabel {
            get {
                return ResourceManager.GetString("EmailTemplateNewAppUserWelcomeVerifyEmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email templates.
        /// </summary>
        internal static string EmailTemplateSettingsPanel {
            get {
                return ResourceManager.GetString("EmailTemplateSettingsPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When a user wants to reset password, send the reset link in email:.
        /// </summary>
        internal static string EmailTemplateUserForgotPasswordLabel {
            get {
                return ResourceManager.GetString("EmailTemplateUserForgotPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is sending messages service active? .
        /// </summary>
        internal static string IsSendingMessagesActive {
            get {
                return ResourceManager.GetString("IsSendingMessagesActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail server requires authentication?.
        /// </summary>
        internal static string MailServerAuthenticationLabel {
            get {
                return ResourceManager.GetString("MailServerAuthenticationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail server host name:.
        /// </summary>
        internal static string MailServerHostNameLabel {
            get {
                return ResourceManager.GetString("MailServerHostNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail account password:.
        /// </summary>
        internal static string MailServerPasswordLabel {
            get {
                return ResourceManager.GetString("MailServerPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail server port:.
        /// </summary>
        internal static string MailServerPortLabel {
            get {
                return ResourceManager.GetString("MailServerPortLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail server uses SSL?.
        /// </summary>
        internal static string MailServerSslLabel {
            get {
                return ResourceManager.GetString("MailServerSslLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail account username:.
        /// </summary>
        internal static string MailServerUserNameLabel {
            get {
                return ResourceManager.GetString("MailServerUserNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail settings.
        /// </summary>
        internal static string MailSettingsPanel {
            get {
                return ResourceManager.GetString("MailSettingsPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maxium difference for time matching: &lt;sup&gt;(In minutes)&lt;/sup&gt;.
        /// </summary>
        internal static string MatchDateDiffLabel {
            get {
                return ResourceManager.GetString("MatchDateDiffLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radius for matching &quot;from&quot; address:&lt;sup&gt;(in meters)&lt;/sup&gt;.
        /// </summary>
        internal static string MatchRadiusFromLabel {
            get {
                return ResourceManager.GetString("MatchRadiusFromLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radius for matching &quot;to&quot; address:&lt;sup&gt;(in meters)&lt;/sup&gt;.
        /// </summary>
        internal static string MatchRadiusToLabel {
            get {
                return ResourceManager.GetString("MatchRadiusToLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings were saved. Please make sure that all is well..
        /// </summary>
        internal static string MessageSaveSuccess {
            get {
                return ResourceManager.GetString("MessageSaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test email was not sent. An error occurred:\n{0}.
        /// </summary>
        internal static string MessageTestMailFailed {
            get {
                return ResourceManager.GetString("MessageTestMailFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test email was sent successfully to {0}..
        /// </summary>
        internal static string MessageTestMailSuccess {
            get {
                return ResourceManager.GetString("MessageTestMailSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min price for ofeer bid.
        /// </summary>
        internal static string OfferMinPrice {
            get {
                return ResourceManager.GetString("OfferMinPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy Url.
        /// </summary>
        internal static string PrivacyPolicyUrlLabel {
            get {
                return ResourceManager.GetString("PrivacyPolicyUrlLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save settings!.
        /// </summary>
        internal static string SaveButton {
            get {
                return ResourceManager.GetString("SaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm that you want to save.
        /// </summary>
        internal static string SaveConfirmLabel {
            get {
                return ResourceManager.GetString("SaveConfirmLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you want to save settings, you must confirm using the checkbox :-).
        /// </summary>
        internal static string SaveConfirmRequired {
            get {
                return ResourceManager.GetString("SaveConfirmRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secure upload local folder:.
        /// </summary>
        internal static string SecureUploadFolderLabel {
            get {
                return ResourceManager.GetString("SecureUploadFolderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special settings.
        /// </summary>
        internal static string SpecialSettingsPanel {
            get {
                return ResourceManager.GetString("SpecialSettingsPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporary uploads local folder:.
        /// </summary>
        internal static string TempUploadFolderLabel {
            get {
                return ResourceManager.GetString("TempUploadFolderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test mail settings.
        /// </summary>
        internal static string TestMailButton {
            get {
                return ResourceManager.GetString("TestMailButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web console root url:.
        /// </summary>
        internal static string WebRootUrlLabel {
            get {
                return ResourceManager.GetString("WebRootUrlLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General web settings.
        /// </summary>
        internal static string WebSettingsPanel {
            get {
                return ResourceManager.GetString("WebSettingsPanel", resourceCulture);
            }
        }
    }
}
