//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Snoopi.web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Users {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Users() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Snoopi.web.Resources.Users", typeof(Users).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete user!.
        /// </summary>
        internal static string DeleteUserButton {
            get {
                return ResourceManager.GetString("DeleteUserButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes I am sure..
        /// </summary>
        internal static string DeleteUserConfirmCheckbox {
            get {
                return ResourceManager.GetString("DeleteUserConfirmCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this user and all of its data?.
        /// </summary>
        internal static string DeleteUserConfirmLabel {
            get {
                return ResourceManager.GetString("DeleteUserConfirmLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot delete this user without confirming that you know what you are doing..
        /// </summary>
        internal static string DeleteUserConfirmRequired {
            get {
                return ResourceManager.GetString("DeleteUserConfirmRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete user &lt;i&gt;{0}&lt;/i&gt;.
        /// </summary>
        internal static string DeleteUserPageTitle {
            get {
                return ResourceManager.GetString("DeleteUserPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit a user account.
        /// </summary>
        internal static string EditUserPageTitle {
            get {
                return ResourceManager.GetString("EditUserPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked?.
        /// </summary>
        internal static string IsLocked {
            get {
                return ResourceManager.GetString("IsLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last logged in.
        /// </summary>
        internal static string LastLogin {
            get {
                return ResourceManager.GetString("LastLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create user, this email address is already registered with another user..
        /// </summary>
        internal static string MessageCreateFailedAlreadyExists {
            get {
                return ResourceManager.GetString("MessageCreateFailedAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create user, you have supplied an invalid email address..
        /// </summary>
        internal static string MessageCreateFailedEmailAddressInvalid {
            get {
                return ResourceManager.GetString("MessageCreateFailedEmailAddressInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create user, an unknown error occurred..
        /// </summary>
        internal static string MessageCreateFailedUnknown {
            get {
                return ResourceManager.GetString("MessageCreateFailedUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot change email address. This email address is probably registered with another user..
        /// </summary>
        internal static string MessageEmailChangeFailed {
            get {
                return ResourceManager.GetString("MessageEmailChangeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data here. No users. Sounds weird? It is. You might want to contact a system administrator, have it checked out....
        /// </summary>
        internal static string MessageNoDataHere {
            get {
                return ResourceManager.GetString("MessageNoDataHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot change password, the current password do not match the password you supplied..
        /// </summary>
        internal static string MessagePasswordChangeBadOldPassword {
            get {
                return ResourceManager.GetString("MessagePasswordChangeBadOldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot change password, an unknown error has occurred..
        /// </summary>
        internal static string MessagePasswordChangeFailedUnknown {
            get {
                return ResourceManager.GetString("MessagePasswordChangeFailedUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user account was created successfully..
        /// </summary>
        internal static string MessageUserCreated {
            get {
                return ResourceManager.GetString("MessageUserCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user account was saved successfully..
        /// </summary>
        internal static string MessageUserSaved {
            get {
                return ResourceManager.GetString("MessageUserSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New user.
        /// </summary>
        internal static string NewUserButton {
            get {
                return ResourceManager.GetString("NewUserButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new user account.
        /// </summary>
        internal static string NewUserPageTitle {
            get {
                return ResourceManager.GetString("NewUserPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage database backup and restores.
        /// </summary>
        internal static string Perm_sys_backups {
            get {
                return ResourceManager.GetString("Perm_sys_backups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage app users.
        /// </summary>
        internal static string Perm_sys_edit_appusers {
            get {
                return ResourceManager.GetString("Perm_sys_edit_appusers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage email templates and logs.
        /// </summary>
        internal static string Perm_sys_edit_emails {
            get {
                return ResourceManager.GetString("Perm_sys_edit_emails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage users.
        /// </summary>
        internal static string Perm_sys_edit_users {
            get {
                return ResourceManager.GetString("Perm_sys_edit_users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage system settings.
        /// </summary>
        internal static string Perm_sys_settings {
            get {
                return ResourceManager.GetString("Perm_sys_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View app users.
        /// </summary>
        internal static string Perm_sys_view_appusers {
            get {
                return ResourceManager.GetString("Perm_sys_view_appusers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View email templates and logs.
        /// </summary>
        internal static string Perm_sys_view_emails {
            get {
                return ResourceManager.GetString("Perm_sys_view_emails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View users.
        /// </summary>
        internal static string Perm_sys_view_users {
            get {
                return ResourceManager.GetString("Perm_sys_view_users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissions.
        /// </summary>
        internal static string PermissionsPanel {
            get {
                return ResourceManager.GetString("PermissionsPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save user.
        /// </summary>
        internal static string SaveButton {
            get {
                return ResourceManager.GetString("SaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password: &lt;sup&gt;(If you want to change it)&lt;/sup&gt;.
        /// </summary>
        internal static string UserCurrentPasswordLabel {
            get {
                return ResourceManager.GetString("UserCurrentPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please supply a valid email user email address..
        /// </summary>
        internal static string UserEmailInvalid {
            get {
                return ResourceManager.GetString("UserEmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address: &lt;sup&gt;Used for login&lt;/sup&gt;.
        /// </summary>
        internal static string UserEmailLabel {
            get {
                return ResourceManager.GetString("UserEmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User email address is required..
        /// </summary>
        internal static string UserEmailRequired {
            get {
                return ResourceManager.GetString("UserEmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked?.
        /// </summary>
        internal static string UserLockedLabel {
            get {
                return ResourceManager.GetString("UserLockedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The repeated password does not match the original. Please make sure that your type your password correctly both times..
        /// </summary>
        internal static string UserNewPasswordConfirmInvalid {
            get {
                return ResourceManager.GetString("UserNewPasswordConfirmInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat the new password: &lt;sup&gt;Please :-)&lt;/sup&gt;.
        /// </summary>
        internal static string UserNewPasswordConfirmLabel {
            get {
                return ResourceManager.GetString("UserNewPasswordConfirmLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to repeat the password. This is to make sure you typed it right..
        /// </summary>
        internal static string UserNewPasswordConfirmRequired {
            get {
                return ResourceManager.GetString("UserNewPasswordConfirmRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password:.
        /// </summary>
        internal static string UserNewPasswordLabel {
            get {
                return ResourceManager.GetString("UserNewPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A password is required for the new user..
        /// </summary>
        internal static string UserNewPasswordRequired {
            get {
                return ResourceManager.GetString("UserNewPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total number of users found:.
        /// </summary>
        internal static string UsersCountLabel {
            get {
                return ResourceManager.GetString("UsersCountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users management.
        /// </summary>
        internal static string UsersPageTitle {
            get {
                return ResourceManager.GetString("UsersPageTitle", resourceCulture);
            }
        }
    }
}
