/* dgTools library by Daniel Cohen Gindi (danielgindi@gmail.com) 054-5655765 */
/* Version: 2012-10-29 */
$isElement=function(a){return a&&1==a.nodeType};$isArray=function(a){return null!=a&&"object"==typeof a&&"splice"in a&&"join"in a};$isFunction=function(a){return"function"==typeof a};$isString=function(a){return"string"==typeof a};$isNumber=function(a){return"number"==typeof a};$Array=function(a){if(!a.length)return[];for(var d=[],b=0;b<a.length;b++)d.push(a[b]);return d};
(function(){var a=Array.prototype,d=Object.prototype,b=String.prototype;a.indexOf||(a.indexOf=function(a,d){var b=this.length;void 0===d&&(d=0);0>d&&(d+=b);for(0>d&&(d=0);d<b;d++)if(d in this&&this[d]===a)return d;return-1});a.lastIndexOf||(a.lastIndexOf=function(a,d){var b=this.length;void 0===d&&(d=b-1);0>d&&(d+=b);for(d>=b&&(d=b-1);0<=d;)if(d in this&&this[d--]===a)return d;return-1});a.forEach||(a.forEach=function(a,d){for(var b=0,l=this.length;b<l;b++)b in this&&(d?a.call(d,this[b],b,this):a(this[b],
b))});a.every||(a.every=function(a,d){for(var b=0,l=this.length;b<l;b++)if(b in this&&!a.call(d,this[b],b,this))return!1;return!0});a.some||(a.some=function(a,d){for(var b=0,l=this.length;b<l;b++)if(b in this&&a.call(d,this[b],b,this))return!0;return!1});a.map||(a.map=function(a,d){for(var b=Array(this.length),l=0,q=this.length;l<q;l++)l in this&&(b[l]=a.call(d,this[l],l,this));return b});a.filter||(a.filter=function(a,d){for(var b=[],l,q=0,s=this.length;q<s;q++)q in this&&a.call(d,l=this[q],q,this)&&
b.push(l);return b});a.reduce||(a.reduce=function(a,d){void 0===d&&(d=this[0]);for(var b=0,l=this.length;b<l;b++)d=a.call(void 0,d,this[b],b,this);return d});a.reduceRight||(a.reduceRight=function(a,d){var b=this.length;void 0===d&&(d=this[b-1]);for(b-=1;0<=b;b--)d=a.call(void 0,d,this[b],b,this);return d});b.trim||(b.trim=function(){return this.replace(/^\s*|\s*$/g,"")});d.hasOwnProperty||(d.hasOwnProperty=function(a){return"undefined"!==typeof this[a]})})();
(function(){var a=Array.prototype,d=String.prototype,b=Function.prototype,e=Number.prototype;a.iterate=a.forEach;a.contains=function(a,d){return-1!=this.indexOf(a,d)};a.copy=function(a,d){a=a||0;0>a&&(a=this.length+a);for(var d=d||this.length-a,b=[],e=0;e<d;e++)b[e]=this[a++];return b};a.remove=function(a){for(var d=0,b=this.length;d<b;)this[d]===a?(this.splice(d,1),b--):d++;return this};a.insertBefore=function(a,d){0>d?d=0:d>this.length&&(d=this.length);var b=this.splice(d,this.length-d);this.push(a);
for(var e=0;e<b.length;e++)this.push(b[e]);return this};a.findAll=a.filter;a.pluck=function(a){var d=[];this.iterate(function(b){d.push(b[a])});return d};a.reject=function(a,d){var a=a.bind(d),b=[];this.iterate(function(d){a(d)||b.push(d)});return b};a.max=function(){var a;this.iterate(function(d){if(null==a||d>=a)a=d});return a};a.min=function(){var a;this.iterate(function(d){if(null==a||d<a)a=d});return a};a.invoke=function(a){var d=$Array(arguments).slice(1),b=[];this.iterate(function(e){b.push(e[a].apply(e,
d))});return b};a.concat=function(){for(var a=[],d=0,b=this.length;d<b;d++)a.push(this[d]);d=0;for(b=arguments.length;d<b;d++)if($isArray(arguments[d]))for(var e=0,h=arguments[d].length;e<h;e++)a.push(arguments[d][e]);else a.push(arguments[d]);return a};b.bind=function(a,d){var b=this;if(b.__boundAlready)return b;var e=function(){return b.apply(a,d||arguments)};e.__boundAlready=!0;return e};d.escapeForJs||(d.escapeForJs=function(){return void 0===this||null===this?"":this.replace(/\\/g,"\\\\").replace(/\'/g,
"\\'").replace(/\"/g,'\\"').replace(/\r/g,"\\r").replace(/\n/g,"\\n")});d.validateEmail||(d.validateEmail=function(){return!!this.match(/^[A-Z0-9\._%+\-]+@[A-Z0-9\-]+(\.[A-Z0-9\-]+)*$/i)});d.camelize||(d.camelize=function(){var a=this.split("-"),d=a.length;if(1==d)return a[0];for(var b="-"==this.charAt(0)?a[0].charAt(0).toUpperCase()+a[0].substring(1):a[0],e=1;e<d;e++)b+=a[e].charAt(0).toUpperCase()+a[e].substring(1);return b});d.dasherize||(d.dasherize=function(){return this.replace(/[A-Z]/g,function(a){return"-"+
a.toLowerCase()})});d.toArray||(d.toArray=function(){return this.split("")});d.htmlEncode||(d.htmlEncode=function(){return this.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/'/g,"&#39;").replace(/"/g,"&quot;")});e.abs||(e.abs=function(){return Math.abs(this)});e.round||(e.round=function(){return Math.round(this)});e.ceil||(e.ceil=function(){return Math.ceil(this)});e.floor||(e.floor=function(){return Math.floor(this)});e.toPaddedString||(e.toPaddedString=function(a,d){for(var b=
this.toString(d||10),e="",h=a-b.length,t=0;t<h;t++)e+="0";return e+b});if(!d.regexEscape){var h=/([\/()[\]?{}|*+-\:])/g;d.regexEscape=function(){return this.replace(h,"\\$1")}}})();Array.fromElement=function(a){for(var d=[],b=0,e=a.length;b<e;b++)d[b]=a[b];return d};if(window.ActiveXObject){var f=0,i=0,j=navigator.appVersion.indexOf("MSIE ");-1<j&&(j=navigator.appVersion.substr(j+5,3),f=parseFloat(j),i=parseInt(j,10),window.ie=f,window["ie"+f]=f,window["ie"+i]=f)}window.Opera=!!window.opera;
window.Gecko=-1<navigator.userAgent.indexOf("Gecko")&&-1==navigator.userAgent.indexOf("KHTML");window.Firefox=-1<navigator.userAgent.indexOf("Firefox");window.Firefox&&(i=f=0,j=navigator.appVersion.indexOf("Firefox/"),-1<j&&(j=navigator.appVersion.substr(j+8).split(/\, /)[0],f=parseFloat(j),i=parseInt(j,10),window.Firefox=f,window.Firefox["Firefox"+f]=f,window.Firefox["Firefox"+i]=f));window.WebKit=-1<navigator.userAgent.indexOf("AppleWebKit/");window.MobileSafari=!!navigator.userAgent.match(/Apple.*Mobile.*Safari/);
window.getClientHeight=function(){return document.documentElement&&document.documentElement.clientHeight?document.documentElement.clientHeight:document.body&&document.body.clientHeight?document.body.clientHeight:window.innerHeight};window.getClientWidth=function(){return document.documentElement&&document.documentElement.clientWidth?document.documentElement.clientWidth:document.body&&document.body.clientWidth?document.body.clientWidth:window.innerWidth};
window.getClientScrollHeight=function(){return document.documentElement&&document.documentElement.scrollHeight?document.documentElement.scrollHeight:document.body&&document.body.scrollHeight?document.body.scrollHeight:window.scrollHeight};window.getClientScrollWidth=function(){return document.documentElement&&document.documentElement.scrollWidth?document.documentElement.scrollWidth:document.body&&document.body.scrollWidth?document.body.scrollWidth:window.scrollWidth};
window.getScrollOffsets=function(){var a=[window.pageXOffset||document.documentElement.scrollLeft||document.body.scrollLeft,window.pageYOffset||document.documentElement.scrollTop||document.body.scrollTop];a.left=a[0];a.top=a[1];return a};
(function(){if(window.ClassClass&&Class.extend)return Class;var a=!1,d=/xyz/.test(function(){xyz})?/\b_super\b/:/.*/;this.Class=function(){};Class.extend=function(b){function e(){!a&&this.init&&this.init.apply(this,arguments)}var h=this.prototype;a=!0;var n=new this;a=!1;for(var l in b)n[l]="function"==typeof b[l]&&"function"==typeof h[l]&&d.test(b[l])?function(a,d){return function(){var b=this._super;this._super=h[a];var e=d.apply(this,arguments);this._super=b;return e}}(l,b[l]):b[l];e.prototype=
n;e.prototype.constructor=e;e.extend=arguments.callee;return e}})();
(function(){var a,d={$:function(g){if(1<arguments.length){for(var a=0,b=[],k=arguments.length;a<k;a++)b.push(d.$(arguments[a]));return b}if($isArray(g)){a=0;b=[];for(k=g.length;a<k;a++)b.push(d.$(g[a]));return b}return!g?null:g&&1==g.nodeType?g:"string"==typeof g?document.getElementById?document.getElementById(g):document.layers?document.layers[g]:document.all[g]:null},observe:function(g,a,d,b){if(null!=g){if(0==a.indexOf("dom:",0)){var e=function(g){g=g||event;a==g.eventName&&d(g)};g.addEventListener?
g.addEventListener("dataavailable",e,b?!0:!1):g.attachEvent&&g.attachEvent("ondataavailable",e)}else g.__observers||(g.__observers={}),g.__observers[a]||(g.__observers[a]=[]),g.__observers[a].push({f:d,c:b?!0:!1}),g.addEventListener?(g.addEventListener(a,d,b?!0:!1),"mousewheel"==a&&g.addEventListener("DOMMouseScroll",d,b?!0:!1)):g.attachEvent&&g.attachEvent("on"+a,d);return d}},unobserve:function(g,a,d,b){if(null!=g)if(d){if(b=b?!0:!1,g.removeEventListener?(g.removeEventListener(a,d,b),"mousewheel"==
a&&g.removeEventListener("DOMMouseScroll",d,b)):g.detachEvent&&g.detachEvent("on"+a,d),g.__observers&&g.__observers[a]){h=g.__observers[a];for(l=0;l<h.length;l++){var e=h[l];e&&e.f==d&&e.c==b&&g.__observers[a].remove(e)}}}else if(g.__observers&&g.__observers[a]){var h=g.__observers[a];g.__observers[a]=null;for(var l=0;l<h.length;l++)h[l]&&(g.removeEventListener?("mousewheel"==a&&g.removeEventListener("DOMMouseScroll",h[l].f,h[l].c),g.removeEventListener(a,h[l].f,h[l].c)):g.detachEvent&&g.detachEvent("on"+
a,h[l].f))}},hover:function(g,r,b){var k={};r&&(k.mouseover=d.observe(g,"mouseover",function(b){b=new d.Event(b);b.relatedTarget==g||a.hasChild(g,b.relatedTarget)||r.bind(g)(b)}));b&&(k.mouseout=d.observe(g,"mouseout",function(r){r=new d.Event(r);r.relatedTarget==g||a.hasChild(g,r.relatedTarget)||b.bind(g)(r)}));g.__observers||(g.__observers={});g.__observers.hover||(g.__observers.hover=[]);g.__observers.hover.push(k);return k},unhover:function(a,r){if(r)r.mouseover&&d.unobserve(a,"mouseover",r.mouseover),
r.mouseout&&d.unobserve(a,"mouseout",r.mouseout),a.__observers&&a.__observers.hover&&a.__observers.hover.remove(r);else if(a.__observers&&a.__observers.hover){var b=a.__observers.hover;a.__observers.hover=null;for(var k=0;k<b.length;k++)b[k]&&(r=b[k],r.mouseover&&d.unobserve(a,"mouseover",r.mouseover),r.mouseout&&d.unobserve(a,"mouseout",r.mouseout))}},fire:function(a,d){a==document&&(document.createEvent&&!a.dispatchEvent)&&(a=document.documentel);var b;document.createEvent?(b=document.createEvent("HTMLEvents"),
b.initEvent("dataavailable",!0,!0)):(b=document.createEventObject(),b.eventType="ondataavailable");b.eventName=d;document.createEvent?a.dispatchEvent(b):a.fireEvent(b.eventType,b);return b},createFunction:function(a){return"function"==typeof a?a:new Function(a)},extend:function(){if("string"==typeof arguments[1]){var a=arguments[0],d=arguments[1],b=arguments[2],k=arguments[3];"string"==typeof d&&(d=d.split(" "));for(var e,h=0;h<d.length;h++)e=d[h],b&&void 0!==b[e]?a[e]=b[e]:k&&void 0!==k[e]&&(a[e]=
k[e])}else{a=arguments[0];for(h=1;h<arguments.length;h++)if(b=arguments[h])for(d in b)b.hasOwnProperty(d)&&(a[d]=b[d])}return a},binarySearch:function(a,d,b,k){for(var b=void 0===b?0:b,k=void 0===k?a.length:k,e;b<k;)e=b+k>>1,a[e]<d?b=e+1:k=e;return b},path2obj:function(a,d){for(var b=a.split("."),d=d||global,k=0,e=b.length;d&&k<e;k++)d=d[b[k]];return d},easyAnimate:function(a,b,G,k,e,h,l){return d.animate(a,{from:b,to:G,duration:k,fps:e,complete:h,transition:l})}};a={head:function(){for(var a=document.head||
document.firstChild;a&&"HEAD"!=a.tagName;)a=a.nextSibling;return a},hasClassName:function(a,d){var b=a.className;return b.length&&-1<(" "+b+" ").indexOf(" "+d+" ")},addClassName:function(g,d){a.hasClassName(g,d)||(g.className+=(g.className?" ":"")+d);return g},removeClassName:function(a,d){a.className=a.className.replace(RegExp("(^|\\s+)"+d+"(\\s+|$)")," ").trim();return a},getByClassName:function(g,d){for(var b=[],k=g.getElementsByTagName("*"),e=0,h=k.length;e<h;e++)a.hasClassName(k[e],d)&&b.push(k[e]);
return b},forceRerendering:function(a){try{var d=document.createTextNode(" ");a.appendChild(d);a.removeChild(d)}catch(b){}return a},offset:function(a,d){if(!d&&a.pageX)return[a.pageLeft,a.pageTop];for(var b=0,k=0;a!=d&&null!=a;)b+=a.offsetLeft,k+=a.offsetTop,a=a.offsetParent;return[b,k]},positionedOffset:function(g){var d=0,b=0,k;do if(d+=g.offsetTop||0,b+=g.offsetLeft||0,g=g.offsetParent){if("BODY"==g.tagName)break;k=a.css(g,"position");if("static"!==k)break}while(g);g=[b,d];g.left=g[0];g.top=g[1];
return g},offsetParent:function(g){for(g=g.offsetParent||document.body;g&&!("BODY"==g.nodeName||"HTML"==g.nodeName)&&"static"==a.css(g,"position");)g=g.offsetParent;return g},position:function(g){if(!g)return null;var d=a.offsetParent(g),b=a.realOffset(g),k="BODY"==d.nodeName||"HTML"==d.nodeName?{top:0,left:0}:a.realOffset(d);b.top-=parseFloat(a.css(g,"marginTop"))||0;b.left-=parseFloat(a.css(g,"marginLeft"))||0;k.top+=parseFloat(a.css(d,"borderTopWidth"))||0;k.left+=parseFloat(a.css(d,"borderLeftWidth"))||
0;return{top:b.top-k.top,left:b.left-k.left}},realOffset:function(g){var b;if(!g||!g.ownerDocument)return null;try{b=g.getBoundingClientRect()}catch(e){}var k=g.ownerDocument,h=k.documentElement;if(!b||!a.hasChild(h,g))return b?{top:b.top,left:b.left}:{top:0,left:0};g=k.body;k=k.defaultView||k.parentWindow;return{top:b.top+(k.pageYOffset||d.support.boxModel&&h.scrollTop||g.scrollTop)-(h.clientTop||g.clientTop||0),left:b.left+(k.pageXOffset||d.support.boxModel&&h.scrollLeft||g.scrollLeft)-(h.clientLeft||
g.clientLeft||0)}},width:function(g){return a.clientWidth(g)},height:function(g){return a.clientHeight(g)},size:function(g){return a.clientSize(g)},clientSize:function(g){var g=d.$(g),b=a.css(g,"display");if("none"!=b&&null!=b)return{width:g.clientWidth,height:g.clientHeight};var b=null,e=g.style,k=e.visibility,h=e.position,l=e.display;e.visibility="hidden";e.position="absolute";e.display="block";g.clientWidth&&(b={width:g.clientWidth,height:g.clientHeight});null===b&&(b={width:parseFloat(a.css(g,
"width"))+parseFloat(a.css(g,"padding-left"))+parseFloat(a.css(g,"padding-right")),height:parseFloat(a.css(g,"height"))+parseFloat(a.css(g,"padding-top"))+parseFloat(a.css(g,"padding-bottom"))});e.display=l;e.position=h;e.visibility=k;return b},totalSize:function(g){var g=d.$(g),b=a.css(g,"display");if("none"!=b&&null!=b)return{width:g.offsetWidth,height:g.offsetHeight};var b=null,e=g.style,k=e.visibility,h=e.position,l=e.display;e.visibility="hidden";e.position="absolute";e.display="block";g.offsetWidth&&
(b={width:g.offsetWidth,height:g.offsetHeight});null===b&&(b=a.clientSize(g),g.width+=parseFloat(a.css(g,"border-left-width"))+parseFloat(a.css(g,"border-right-width")),g.height+=parseFloat(a.css(g,"border-top-width"))+parseFloat(a.css(g,"border-bottom-width")));e.display=l;e.position=h;e.visibility=k;return b},clientHeight:function(g){return a.clientSize(g).height},totalHeight:function(g){return a.totalSize(g).height},clientWidth:function(g){return a.clientSize(g).width},totalWidth:function(g){return a.totalSize(g).width},
hasChild:function(g,d){for(var b=0,e=g.childNodes,h=e.length;b<h;b++)if(e[b]==d||a.hasChild(e[b],d))return!0;return!1},setText:function(a,d){a&&(void 0!=a.textContent?a.textContent=d:void 0!=a.innerText?a.innerText=d:a.value=d);return a},getText:function(a){return a?void 0!=a.textContent?a.textContent:void 0!=a.innerText?a.innerText:a.value:""},clearFileInputField:function(a){a=d.$(a);try{return a.setAttribute("type","text"),a.setAttribute("type","file"),a}catch(b){var e=a.nextSibling,k=a.parentNode,
h;h=a.cloneNode();k.removeChild(a);e?k.insertBefore(h,e):k.appendChild(h);return h}},hideSelectsIe6:function(g){if(!window.ie||6.5<window.ie)return!1;if(g){for(var g=document.documentElement.getElementsByTagName("select"),d=[],b=0;b<g.length;b++)d.push([g[b],g[b].style.visibility]),g[b].style.visibility="hidden";a.hideSelectsIe6.hidden=d}else{d=a.hideSelectsIe6.hidden||[];for(b=0;b<d.length;b++)d[b][0].style.visibility=d[b][1],d[b]=null;a.hideSelectsIe6.hidden=!1}},hideEmbeds:function(g){if(g){for(var g=
[],d=document.documentElement.getElementsByTagName("embed"),b=document.documentElement.getElementsByTagName("object"),e=0;e<d.length;e++)g.push(d[e]);for(e=0;e<b.length;e++)g.push(b[e]);d=[];for(b=0;b<g.length;b++)d.push([g[b],g[b].style.visibility]),g[b].style.visibility="hidden";a.hideEmbeds.hidden=d}else{d=a.hideEmbeds.hidden||[];for(b=0;b<d.length;b++)d[b][0].style.visibility=d[b][1],d[b]=null;a.hideEmbeds.hidden=!1}},build:function(g,b,e){g=document.createElement(g);if(b)if(b instanceof Array)for(var k=
0;k<b.length;k+=2){var h=b[k];if("className"==h||"class"==h)g.className=b[k+1];else if("innerHTML"==h)g.innerHTML=b[k+1];else if("innerText"==h||"textContent"==h)a.setText(g,b[k+1]);else if("onclick"==h)g.onclick=d.createFunction(b[k+1]);else if("onfocus"==h)g.onfocus=d.createFunction(b[k+1]);else if("onblur"==h)g.onblur=d.createFunction(b[k+1]);else if("onsubmit"==h)g.onsubmit=d.createFunction(b[k+1]);else if("onkeyup"==h)g.onkeyup=d.createFunction(b[k+1]);else if("style"==h)for(var h=b[k+1].split(";"),
l=0;l<h.length;l++){var n=h[l].indexOf(":");if(-1<n){var q=h[l].substr(0,n).trim().camelize(),n=h[l].substr(n+1).trim();0<q.length&&(g.style[q]=n)}}else g.setAttribute(h,b[k+1])}else for(k in b)if(b.hasOwnProperty(k))if("className"==k||"class"==k)g.className=b[k];else if("innerHTML"==k)g.innerHTML=b[k];else if("text"==k||"innerText"==k||"textContent"==k)a.setText(g,b[k]);else if("onclick"==k)g.onclick=d.createFunction(b[k]);else if("onfocus"==k)g.onfocus=d.createFunction(b[k]);else if("onblur"==k)g.onblur=
d.createFunction(b[k]);else if("onsubmit"==k)g.onsubmit=d.createFunction(b[k]);else if("onkeyup"==k)g.onkeyup=d.createFunction(b[k]);else if("css"==k||"styles"==k||"style"==k)if("string"==typeof b[k]){h=b[k].split(";");for(l=0;l<h.length;l++)n=h[l].indexOf(":"),-1<n&&(q=h[l].substr(0,n).trim().camelize(),n=h[l].substr(n+1).trim(),0<q.length&&(g.style[q]=n))}else a.css(g,b[k]);else g.setAttribute(k,b[k]);if(g&&e){void 0===e.length&&(e=[e]);for(k=0;k<e.length;k++)g.appendChild(e[k])}return g},show:function(g){if(g){var d=
g.__originalDisplay;g.__originalDisplay=null;g.style.display=null!=d?d:"";""==g.style.display&&"none"==a.css(g,"display")&&(g.style.display="IMG"==g.tagName||"A"==g.tagName||"SPAN"==g.tagName?"inline-block":"block")}return g},hide:function(a){!a.__originalDisplay&&"none"!=a.style.display&&(a.__originalDisplay=a.style.display);a&&(a.style.display="none");return a},isVisible:function(g){return"none"==a.css(g,"display")||"hidden"==a.css(g,"visibility")?!1:!0},makePositioned:function(g){var d=a.css(g,
"position");if("static"==d||!d)g.__madePositioned=!0,g.__originalPosition=g.style.position,g.style.position="relative",window.Opera&&(g.__originalTop=g.style.top,g.__originalLeft=g.style.left,g.__originalRight=g.style.bottom,g.__originalBottom=g.style.right,g.style.top=0,g.style.left=0,g.style.bottom="",g.style.right="");return g},undoPositioned:function(a){a.__madePositioned&&(a.__madePositioned=void 0,a.style.position=a.__originalPosition,a.__originalPosition=void 0,window.Opera&&(a.style.top=a.__originalTop,
a.style.left=a.__originalLeft,a.style.bottom=a.__originalRight,a.style.right=a.__originalBottom,a.__originalTop=void 0,a.__originalLeft=void 0,a.__originalRight=void 0,a.__originalBottom=void 0));return a},makeClipping:function(g){if(g.__overflow)return this;g.__overflow=a.css(g,"overflow")||"auto";"hidden"!==g.__overflow&&(g.style.overflow="hidden");return g},undoClipping:function(a){if(!a.__overflow)return a;a.style.overflow="auto"==a.__overflow?"":a.__overflow;a.__overflow=null;return a},absolutizePosition:function(g){g=
d.$(g);if("absolute"!=a.css(g,"position")){var b=a.positionedOffset(g),e=b[1],b=b[0],k=g.clientWidth,h=g.clientHeight;g.__madeAbsolute=!0;g.__originalPosition=g.style.position;g.__originalLeft=g.style.left;g.__originalTop=g.style.top;g.__originalRight=g.style.right;g.__originalBottom=g.style.bottom;g.__originalWidth=g.style.width;g.__originalHeight=g.style.height;g.__originalMarginTop=g.style.marginTop;g.__originalMarginLeft=g.style.marginLeft;g.style.position="absolute";g.style.top=e+"px";g.style.left=
b+"px";g.style.width=k+"px";g.style.height=h+"px";g.style.marginTop="0";g.style.marginLeft="0";return g}},undoAbsolutizePosition:function(a){a.__madeAbsolute&&(a.__madeAbsolute=void 0,a.style.position=a.__originalPosition,a.style.left=a.__originalLeft,a.style.top=a.__originalTop,a.style.bottom=a.__originalRight,a.style.right=a.__originalBottom,a.style.width=a.__originalWidth,a.style.height=a.__originalHeight,a.style.marginTop=a.__originalMarginTop,a.style.marginLeft=a.__originalMarginLeft,a.__originalPosition=
void 0,a.__originalTop=void 0,a.__originalLeft=void 0,a.__originalRight=void 0,a.__originalBottom=void 0,a.__originalWidth=void 0,a.__originalHeight=void 0,a.__originalMarginTop=void 0,a.__originalMarginLeft=void 0);return a},cleanWhitespace:function(a){for(var a=d.$(a),b=a.firstChild;b;){var e=b.nextSibling;3==b.nodeType&&!/\S/.test(b.nodeValue)&&a.removeChild(b);b=e}return a},firstRealChild:function(a){for(a=d.$(a).firstChild;a&&1!=a.nodeType;)a=a.nextSibling;return a},ancestors:function(a,b){b&&
(b=b.toUpperCase());for(var a=d.$(a),e=[];a=a.parentNode;)1==a.nodeType&&(!b||a.tagName==b)&&e.push(a);return e},direction:function(b){var d="ltr";do d=a.css(b,"direction"),b=b.parentNode;while("rtl"!=d&&"ltr"!=d&&b);return d}};window.dgTools=d;d.dom=a;var b=null;a.scrollbarSize=function(){if(!b){var a,d;d=document.createElement("p");d.style.width="100%";d.style.height="200px";var e=document.createElement("div");e.style.position="absolute";e.style.top="0px";e.style.left="0px";e.style.visibility="hidden";
e.style.width="200px";e.style.height="150px";e.style.overflow="hidden";e.appendChild(d);document.body.appendChild(e);var k=d.offsetWidth;e.style.overflow="scroll";var h=d.offsetWidth;k==h&&(h=e.clientWidth);a=k-h;d.style.width="200px";d.style.height="100%";e.style.width="150px";e.style.height="200px";e.style.overflow="hidden";k=d.offsetHeight;e.style.overflow="scroll";h=d.offsetHeight;k==h&&(h=e.clientHeight);d=k-h;document.body.removeChild(e);b={width:a,height:d}}return b};var e=/<[^>]*>|&[^;]+;/g,
h=RegExp("^[^A-Za-z\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u02b8\u0300-\u0590\u0800-\u1fff\u2c00-\ufb1c\ufe00-\ufe6f\ufefd-\uffff]*[\u0591-\u07ff\ufb1d-\ufdff\ufe70-\ufefc]");a.setDirAttr=function(a,d){var b="",k=!1;void 0===a.value||null===a.value?void 0===a.innerHTML?k=!1:(b=a.innerHTML,k=!0):b=a.value;b=h.test(k?b.replace(e," "):b);a.style.direction=a.dir=b?"rtl":"ltr";d&&(a.style.textAlign=b?"right":"left")};var n=function(a,b){if(a){b=d.extend({},b);!0===b.queue&&(b.queue="default");var e=b.queue?
$isArray(b.queue)?b.queue:t[b.queue]:null;b.queue&&!e&&(e=t[b.queue]=[]);var k={ended:!1,element:a,options:b,queue:e};a.__animations||(a.__animations=[]);a.__animations.push(k);e&&e.push(k);!e||e[0]==k?e?q(e):0<b.delay&&!b.doNotStart?setTimeout(function(){l(k)},b.delay):l(k):(k.finishNow=k.end=k.step=w,k.cancel=k.stop=function(){a.__animations.remove(k);k.ended=!0;e.remove(k);k.stop=w});return k}},l=function(b){var e=b.options,h=b.element,k=b.queue;if(!b.ended)if(!e.to&&!e.from)e.complete&&e.complete(),
b.ended=!0,b.cancel=b.stop=b.end=b.finishNow=b.step=w;else{b.cancel=b.stop=function(){H&&clearTimeout(H);H=null;b.finishNow=b.stop=b.cancel=b.end=b.step=w;h.__animations.remove(b);q(k,b)};b.end=function(){I()};b.finishNow=function(){I()};b.step=function(a){K(0,a)};e.beforeSetup&&e.beforeSetup();e.transition=e.transition||d.Transitions.sinoidal;"string"==typeof e.transition&&(e.transition=d.Transitions[e.transition]);"function"!=typeof e.transition&&(e.transition=d.Transitions.sinoidal);e.duration=
e.duration||0;0>e.duration&&(e.duration=0);e.fps=e.fps||p;var l=this,n=+new Date,s=[],C=[],t=[],E=[],y=[],F=[],x=e.from||{},D=e.to||{},m;for(m in x)if(x.hasOwnProperty(m))if("left"==m||"top"==m||"right"==m||"bottom"==m||"width"==m||"height"==m||"margin-left"==m||"margin-top"==m||"margin-right"==m||"margin-bottom"==m){var z={};z[m]=parseFloat(x[m])+"px";a.css(h,z);if(("width"==m||"height"==m)&&"inline"==a.css(h,"display"))h.display="inline-block;"}else"scrollLeft"==m||"scrollTop"==m?h[m]=parseFloat(x[m]):
(z={},z[m]=x[m],a.css(h,z));for(m in D)if(D.hasOwnProperty(m)){if("left"==m||"top"==m||"right"==m||"bottom"==m||"width"==m||"height"==m||"margin-left"==m||"margin-top"==m||"margin-right"==m||"margin-bottom"==m){if(s.push(m),y[m]=!0,E[m]="px",x&&void 0!==x[m]&&null!==x[m]?C[m]=parseFloat(x[m]):(C[m]=parseFloat(a.css(h,m)),isNaN(C[m])&&("width"==m?C[m]=parseFloat(a.clientWidth(h)):"height"==m&&(C[m]=parseFloat(a.clientHeight(h))))),t[m]=parseFloat(D[m]),("width"==m||"height"==m)&&"inline"==a.css(h,
"display"))h.display="inline-block;"}else"scrollLeft"==m||"scrollTop"==m?(s.push(m),y[m]=!1,E[m]=0,C[m]=x&&void 0!==x[m]&&null!==x[m]?parseFloat(x[m]):parseFloat(h[m]),t[m]=D[m]):"color"==m||"background-color"==m||"border-top-color"==m||"border-right-color"==m||"border-bottom-color"==m||"border-left-color"==m||"outline-color"==m?(s.push(m),y[m]=!0,E[m]="",F[m]=!0,C[m]=x&&void 0!==x[m]&&null!==x[m]?new d.Color(x[m]):new d.Color(a.css(h,m)),t[m]=new d.Color(D[m])):(s.push(m),y[m]=!0,E[m]="",C[m]=x&&
void 0!==x[m]&&null!==x[m]?x[m]:a.css(h,m),t[m]=D[m]);"string"==typeof t[m]&&(z=t[m],"+"==z[0]&&"="==z[1]?t[m]=C[m]+parseFloat(z.substr(2)):"-"==z[0]&&"="==z[1]&&(t[m]=C[m]-parseFloat(z.substr(2))))}e.start&&e.start();var L=Math.floor(1E3/e.fps),K=function(d,m){var z,p,I={};void 0==m&&(m=(+new Date-n)/e.duration);if(1>m){for(var x=e.transition(m),B=0;B<s.length;B++)p=s[B],z=C[p]+(t[p]-C[p])*x,y[p]?I[p]=F[p]?C[p].colorByTranslatingColor(t[p],x).css():z+E[p]:h[p]=z+E[p];a.css(h,I);e.step&&e.step.call(l,
x);if(e.sync)if($isArray(e.sync)){z=0;for(p=e.sync.length;z<p;z++)e.sync[z].step(m)}else e.sync.step(m);null!==H&&(H=setTimeout(K,L))}else{b.finishNow=b.stop=b.cancel=b.end=b.step=w;for(B=0;B<s.length;B++)p=s[B],y[p]?I[p]=F[p]?t[p].css():t[p]+E[p]:h[p]=t[p]+E[p];a.css(h,I);e.step&&e.step.call(l,1);if(e.sync)if($isArray(e.sync)){z=0;for(p=e.sync.length;z<p;z++)e.sync[z].step(1)}else e.sync.step(1);e.complete&&e.complete(l);void 0!=e.to.opacity&&a.forceRerendering(h);h.__animations.remove(b);q(k,b)}},
I=function(){H&&clearTimeout(H);H=null;n=+new Date-e.duration;K();b.finishNow=b.stop=b.cancel=b.end=b.step=w;h.__animations.remove(b);q(k,b)},H=null;e.doNotStart?b.startAnimation=function(){b.startAnimation=null;H=setTimeout(K,L)}:H=setTimeout(K,L)}},q=function(a,b){a&&(b&&a.remove(b),a.length&&(a[0].options.doNotStart=!1,0<a[0].options.delay&&!options.doNotStart?setTimeout(function(){l(a[0])},a[0].options.delay):l(a[0])))},s=function(a){a||(a="default");if((a=t[a]||($isArray(a)?a:null))&&a.length)for(;a.length;)try{a[a.length-
1].cancel()}catch(b){window.console&&console.log&&console.log(b)}},p=window.MobileSafari?45:66,t={"default":[]},w=function(){return!0};n.shake=function(b,d,e,h,l,p){function w(){y.stop=y.finishNow=y.cancel=y.end=y.step;E&&a.undoPositioned(b);var e={};e[d]=J;a.css(b,e);b.__shaking=null}if(!e||0>=e||!h||0>=h||!l||0>=l)return null;if(!b.__shaking||p){b.__shaking=!0;var t=[],l=l/h,J=a.css(b,d),p=parseFloat(J),E=!1;isNaN(p)&&("left"==d||"top"==d||"right"==d||"bottom"==d?(p=a.css(b,"position"),(E="relative"!=
p&&"absolute"!=p&&"fixed"!=p)&&a.makePositioned(b),p=a.offset(b),p="left"==d||"top"==d?"left"==d?p[0]:p[1]:"right"==d?window.getClientWidth()-p[0]-a.totalWidth(b):window.getClientHeight()-p[1]-a.totalHeight(b)):p=0);for(var y={step:function(){}},F=0,x,D,m=h-1;F<h;F++)x={},D={},x[d]=0==F?p:0==F%2?p-e:p+e,D[d]=F==m?p:0==F%2?p+e:p-e,t.push(n(b,{from:x,to:D,transition:"sinoidalInOut",duration:l,doNotStart:!0,complete:F==m?w:null})),t[F].queue=t;q(t);y.stop=y.finishNow=y.cancel=y.end=function(){y.stop=
y.finishNow=y.cancel=y.end=y.step;s(t);w()};return y}};d.animate=a.animate=n;d.cancelAnimationsFor=a.cancelAnimationsFor=function(a){if(a&&a.__animations){for(;a.__animations.length;)a.__animations[0].cancel();return!0}};d.cancelAnimationQueue=a.cancelAnimationQueue=s;d.finishAnimationQueue=a.finishAnimationQueue=function(a){a||(a="default");if((a=t[a]||($isArray(a)?a:null))&&a.length){for(var b=a.length-1;0<=b;b++)a[b].options.duration=0;if(a.length)try{a[0].finishNow()}catch(d){window.console&&
console.log&&console.log(d)}}}})();null==window.$&&($=dgTools.$);
dgTools.ajax={$:dgTools.$,loadScriptFromUrl:function(a,d,b){var e=null,h=document.getElementsByTagName("head")[0];if(d){var n=!1,d="$ajax_load_"+d;(e=dgTools.$(d))?h.removeChild(e):n=!0;e=document.createElement("script");e.id=d;b&&(d+="_counter$",b=n?0:eval(d),b++,eval(d+"="+b),a=0<=a.indexOf("?")?a+("&_counter$="+b):a+("?_counter$="+b))}else e=document.createElement("script");h.appendChild(e);e.src=a},getScriptElement:function(a,d){for(var b=document.getElementsByTagName("script"),e=0;e<b.length;e++)if(d&&
b[e].src.substr(0,a.length)==a||!d&&b[e].src==a)return b[e];return null},parseXmlString:function(a){var d=null;if(window.ActiveXObject)try{d=new ActiveXObject("Microsoft.XMLDOM"),d.async=!1,d.loadXML(a)}catch(b){}else DOMParser&&(d=(new DOMParser).parseFromString(a,"application/xml"));if(d&&d.documentElement)return d.documentElement},parseXmlFile:function(a){var d=null;if(window.ActiveXObject)try{d=new ActiveXObject("Microsoft.XMLDOM")}catch(b){try{d=document.implementation.createDocument("","",null)}catch(e){}}d.async=
!1;d.load(a);if(d&&d.documentElement)return d.documentElement},loadUrl:function(a,d,b,e,h,n){var l=!!d;"string"==typeof b&&(b=dgTools.ajax.ResponseParsers[b]);b||(b=dgTools.ajax.ResponseParsers.text);var e=e||"GET",q=null;if(!window.ie||"file:"!=location.protocol)try{q=new XMLHttpRequest}catch(s){}if(null==q)try{q=new ActiveXObject("Msxml2.XMLHTTP")}catch(p){}if(null==q)try{q=new ActiveXObject("Microsoft.XMLHTTP")}catch(t){}if(!q)return null;l&&(q.onreadystatechange=function(){4==q.readyState&&(d(b(q)),
q=null)});q.open(e,a,l);if(h)for(var w in h)h.hasOwnProperty(w)&&q.setRequestHeader(w,h[w]);try{q.send(n||null)}catch(g){return null}var r;return r=l?{abort:function(){try{q.abort(),r.abort=function(){}}catch(a){}}}:b(q)},getUrl:function(a,d,b){return dgTools.ajax.loadUrl(a,d,b,"GET")},deleteUrl:function(a,d,b){return dgTools.ajax.loadUrl(a,d,b,"DELETE")},postUrl:function(a,d,b,e,h){return dgTools.ajax.loadUrl(a,e,h,"POST",d,b)},putUrl:function(a,d,b,e,h){return dgTools.ajax.loadUrl(a,e,h,"PUT",d,
b)},loadImage:function(a,d){var b=document.createElement("img"),e=function(){dgTools.unobserve(b,"load",e,!1);dgTools.unobserve(b,"error",h,!1);null!=d&&d(!0,a,b)},h=function(){dgTools.unobserve(b,"load",e,!1);dgTools.unobserve(b,"error",h,!1);null!=d&&d(!1,a,b)};dgTools.observe(b,"load",e,!1);dgTools.observe(b,"error",h,!1);b.src=a;h=e=null;return b},ResponseParsers:{text:function(a){return dgTools.ajax.loadUrl.checkStatus(a)?a.responseText:null},json:function(a){a=dgTools.ajax.ResponseParsers.text(a);
return""==a?null:JSON.parse(a)},xml:function(a){if(dgTools.ajax.loadUrl.checkStatus(a)){var d=a.responseXML;if(!d&&window.ActiveXObject)try{var b=new ActiveXObject("Microsoft.XMLDOM");b.async=!1;b.loadXML(a.responseText)}catch(e){}return d&&d.firstChild?d:dgTools.ajax.parseXmlString(a.responseText)}return null}},obj2url:function(a,d,b){var e=[],h="&",n=function(a,b){var h=d?/\[\]$/.test(d)?d:d+"["+b+"]":b;"undefined"!=h&&"undefined"!=b&&e.push("object"===typeof a?dgTools.ajax.obj2url(a,h,!0):"[object Function]"===
Object.prototype.toString.call(a)?encodeURIComponent(h)+"="+encodeURIComponent(a()):encodeURIComponent(h)+"="+encodeURIComponent(a))};if(!b&&d)h=/\?/.test(d)?/\?$/.test(d)?"":"&":"?",e.push(d),e.push(dgTools.ajax.obj2url(a));else if("[object Array]"===Object.prototype.toString.call(a)&&"undefined"!=typeof a)for(var l=0,b=a.length;l<b;++l)n(a[l],l);else if("undefined"!=typeof a&&null!==a&&"object"===typeof a)for(l in a)n(a[l],l);else e.push(encodeURIComponent(d)+"="+encodeURIComponent(a));return e.join(h).replace(/^&/,
"").replace(/%20/g,"+")}};dgTools.ajax.loadUrl.checkStatus=function(a){return 4==a.readyState&&(200<=a.status&&300>a.status||304==a.status||0===a.status||1223==a.status)};var ajax=dgTools.ajax;
dgTools.Io={getFileName:function(a,d){var b=a.replace(/^.*[\/\\]/g,"");"string"==typeof d&&b.substr(b.length-d.length)==d&&(b=b.substr(0,b.length-d.length));return b},stripHash:function(a){var d=a.indexOf("?");return-1<d?a.substr(0,d):a},getBasePath:function(a){var d=a.indexOf("?");-1==d&&(d=a.length);d=a.lastIndexOf("/",d);return-1==d?"/":a.substr(0,d+1)},isAbsolutePath:function(a){var d=a.indexOf("?");-1==d&&(d=a.length);d=a.lastIndexOf("://",d);return-1==d?!1:!0},findScriptPath:function(a,d){for(var b=
document.getElementsByTagName("script"),e=0;e<b.length;e++){var h=b[e].src;d&&(h=dgTools.Io.stripHash(h));if(dgTools.Io.getFileName(h)==a)return b=h.substring(0,h.lastIndexOf("/")+1),"https:"==document.location.protocol&&!dgTools.Io.isAbsolutePath(b)&&(b=0<b.Length&&"/"==b.charAt(0)?"https://"+document.location.hostname+b:"https://"+document.location.hostname+dgTools.Io.getBasePath(document.location.pathname)+b),b}return""}};
dgTools.Browser={preventBack:function(){setTimeout(function(){window.history.forward()},0);dgTools.observe(window,"unload",function(){null})},isChrome:function(){return document.getElementById&&0<=navigator.appVersion.indexOf("Chrome")},winPopup:function(a,d,b,e,h){if(void 0==e||null==e)e="";d=window.open("",e,config="height="+b+",width="+d+",resizable=no,toolbars=no,address=no,status=no,menubar=no,location=no,toolbar=no,scrollbars=no");try{!0==h&&(d.document.close(),d.document.open())}catch(n){}d.document.location=
a;d.window.focus();return d},simulateInnerAnchorClick:function(a,d){for(var b=0;b<d;b++){if(b<d&&!a.firstChild||b==d&&!a.href)return;b<d&&(a=a.firstChild)}if(a.href)return a.target&&0<a.target.length?window.open(a.href,a.target):document.location=a.href,!1}};
dgTools.Transitions={linearIn:function(a){return a},linearOut:function(a){return a},linearInOut:function(a){return a},sinoidalIn:function(a){return-Math.cos(a*(Math.PI/2))+1},sinoidalOut:function(a){return Math.sin(a*(Math.PI/2))},sinoidalInOut:function(a){return-Math.cos(a*Math.PI)/2+0.5},cubicIn:function(a){return a*a*a},cubicOut:function(a){a--;return a*a*a+1},cubicInOut:function(a){a*=2;if(1>a)return 0.5*a*a*a;a-=2;return 0.5*(a*a*a+2)},quadraticIn:function(a){return a*a},quadraticOut:function(a){return-(a*
(a-2))},quadraticInOut:function(a){a*=2;if(1>a)return 0.5*a*a;a--;return-0.5*(a*(a-2)-1)},quarticIn:function(a){return a*a*a*a},quarticOut:function(a){a--;return-(a*a*a*a-1)},quarticInOut:function(a){a*=2;if(1>a)return 0.5*a*a*a*a;a-=2;return-0.5*(a*a*a*a-2)},quinticIn:function(a){return a*a*a*a*a},quinticOut:function(a){a--;return a*a*a*a*a+1},quinticInOut:function(a){a*=2;if(1>a)return 0.5*a*a*a*a*a;a-=2;return 0.5*(a*a*a*a*a+2)},expoIn:function(a){return Math.pow(2,10*(a-1))},expoOut:function(a){return-Math.pow(2,
-10*a)+1},expoInOut:function(a){a*=2;if(1>a)return 0.5*Math.pow(2,10*(a-1));a--;return 0.5*(-Math.pow(2,-10*a)+2)},circularIn:function(a){return-(Math.sqrt(1-a*a)-1)},circularOut:function(a){a--;return Math.sqrt(1-a*a)},circularInOut:function(a){a*=2;if(1>a)return-0.5*(Math.sqrt(1-a*a)-1);a-=2;return 0.5*(Math.sqrt(1-a*a)+1)},easeInBack:function(a,d){void 0==d&&(d=1.70158);return a*a*((d+1)*a-d)},easeOutBack:function(a,d){void 0==d&&(d=1.70158);return(a-=1)*a*((d+1)*a+d)+1},easeInOutBack:function(a,
d){void 0==d&&(d=1.70158);return 1>(a*=2)?0.5*a*a*(((d*=1.525)+1)*a-d):0.5*((a-=2)*a*(((d*=1.525)+1)*a+d)+2)},easeInBounce:function(a){return 1-dgTools.Transitions.easeOutBounce(1-a)},easeOutBounce:function(a){return a<1/2.75?7.5625*a*a:a<2/2.75?7.5625*(a-=1.5/2.75)*a+0.75:a<2.5/2.75?7.5625*(a-=2.25/2.75)*a+0.9375:7.5625*(a-=2.625/2.75)*a+0.984375},easeInOutBounce:function(a){return 0.5>c?dgTools.Transitions.easeInBounce(2*a)/2:dgTools.Transitions.easeOutBounce(2*a-1)/2+0.5},reverse:function(a){return 1-
a},flicker:function(a){a=-Math.cos(a*Math.PI)/4+0.75+Math.random()/4;return 1<a?1:a},wobble:function(a){return-Math.cos(a*Math.PI*9*a)/2+0.5},pulse:function(a,d){d=d||5;return 0==(a%(1/d)*d).round()?2*a*d-(2*a*d).floor():1-(2*a*d-(2*a*d).floor())},spring:function(a){return 1-Math.cos(4.5*a*Math.PI)*Math.exp(6*-a)},none:function(){return 0},full:function(){return 1}};dgTools.Transitions.def="sinoidalInOut";dgTools.Transitions.swing=dgTools.Transitions.sinoidalInOut;dgTools.Transitions.sinoidal=dgTools.Transitions.sinoidalInOut;
dgTools.Transitions.linear=dgTools.Transitions.linearInOut;dgTools.Transitions.cubic=dgTools.Transitions.cubicInOut;dgTools.Transitions.quadratic=dgTools.Transitions.quadraticInOut;dgTools.Transitions.quartic=dgTools.Transitions.quarticInOut;dgTools.Transitions.quintic=dgTools.Transitions.quinticInOut;dgTools.Transitions.expo=dgTools.Transitions.expoInOut;dgTools.Transitions.circular=dgTools.Transitions.circularInOut;
dgTools.Form={submit:function(a,d){a=dgTools.$(a);if(!a)return!1;var b,e=!0;if(document.createEvent)b=document.createEvent("HTMLEvents"),b.initEvent("submit",!0,!0),e=a.dispatchEvent(b),void 0!==b.defaultPrevented&&(null!==b.defaultPrevented&&b.defaultPrevented)&&(e=!1),void 0!==b.returnValue&&(null!==b.returnValue&&!b.returnValue)&&(e=!1);else if(document.createEventObject)b=document.createEventObject(),e=a.fireEvent("onsubmit",b),void 0!==b.defaultPrevented&&(null!==b.defaultPrevented&&b.defaultPrevented)&&
(e=!1),void 0!==b.returnValue&&(null!==b.returnValue&&!b.returnValue)&&(e=!1);else if(a.onsubmit)if($isFunction(a.onsubmit))e=a.onsubmit.bind(a)();else if($isString(a.onsubmit)){b=null;try{b=eval("(function(){"+a.onsubmit+"})")}catch(h){}b&&(e=b.bind(a)())}return e&&!d?a.submit():!!e},submitOnEnter:function(a,d,b){a=dgTools.$(a);if(!a)return!1;d=d||window.event;if(d.keyCode==dgTools.Event.Keys.enter&&!d.shiftKey&&(!document.activeElement||"TEXTAREA"!=document.activeElement.tagName))if(b=b?b.bind(a)():
dgTools.Form.submit(a,!0))a.submit();else return!1;return!0}};
dgTools.Tables={clear:function(a){for(;a.childNodes.length;)a.removeChild(a.childNodes[0])},clearArea:function(a,d){for(var b=0;b<a.childNodes.length;b++)if(a.childNodes[b].nodeName.toLowerCase()==d.toString().toLowerCase())for(var e=a.childNodes[b];e.childNodes.length;)e.removeChild(e.firstChild)},removeArea:function(a,d){for(var b=0;b<a.childNodes.length;b++)a.childNodes[b].nodeName.toLowerCase()==d.toString().toLowerCase()&&(a.removeChild(a.childNodes[b]),b--)},removeRows:function(a){for(;a.rows.length;)a.deleteRow(0)}};
dgTools.Cookies={save:function(a,d,b){if(b){var e=new Date;e.setTime(e.getTime()+864E5*parseFloat(b));b=e.toUTCString()}else b=null;document.cookie=a+"="+escape(d)+"; path=/"+(null==b?"":"; expires="+b)},read:function(a){var d=document.cookie,a=a+"=";return 0<d.length&&(begin=d.indexOf(a),-1!=begin)?(begin+=a.length,end=d.indexOf(";",begin),-1==end&&(end=d.length),unescape(d.substring(begin,end))):null}};dgTools.Event=function(){return this.init.apply(this,arguments)};
dgTools.Event.fix={relatedTarget:function(){this.relatedTarget&&3==this.relatedTarget.nodeType&&(this.relatedTarget=this.relatedTarget.parentNode)},relatedTargetGecko:function(){try{dgTools.Event.fix.relatedTarget.call(this)}catch(a){this.relatedTarget=this.target}}};
dgTools.Event.Keys={ENTER:13,NUMPAD_ENTER:108,UP:38,DOWN:40,LEFT:37,RIGHT:39,PAGE_UP:33,PAGE_DOWN:34,ESCAPE:27,SPACE:32,BACKSPACE:8,TAB:9,DELETE:46,enter:13,up:38,down:40,left:37,right:39,pageup:33,pagedown:34,esc:27,space:32,backspace:8,tab:9,"delete":46};
dgTools.Event.prototype={init:function(a){if(a&&a.$extended)return a;this.$extended=!0;this.event=a=a||window.event;this.type=a.type;this.target=a.target||a.srcElement;3==this.target.nodeType&&(this.target=this.target.parentNode);this.shift=a.shiftKey;this.control=a.ctrlKey;this.alt=a.altKey;this.meta=a.metaKey;if(["DOMMouseScroll","mousewheel"].contains(this.type))this.wheelY=this.wheelX=0,a.wheelDeltaX||a.wheelDeltaY?(this.wheelX=a.wheelDeltaX/120,this.wheelY=a.wheelDeltaY/120):a.wheelDelta?this.wheelY=
a.wheelDelta/120:a.detail&&(a.axis&&1==a.axis?this.wheelX=-a.detail/3:this.wheelY=-a.detail/3),this.wheel=a.wheelDelta?a.wheelDelta/120:-(a.detail||0)/3;else if(-1<this.type.indexOf("key")){this.code=a.which||a.keyCode;for(var d in dgTools.Event.Keys)if(dgTools.Event.Keys[d]==this.code){this.key=d;break}"keydown"==this.type&&(a=this.code-111,0<a&&13>a&&(this.key="f"+a));this.key=this.key||String.fromCharCode(this.code).toLowerCase()}else if(/(click|mouse|menu)/.test(this.type)){if(a.pageX)this.page=
{x:a.pageX,y:a.pageY};else{if(!document.__rtlIeFlippedScrollX){d=dgTools.dom.css(document.documentElement,"direction");var b=dgTools.dom.css(document.body,"direction");document.__rtlIeFlippedScrollX="rtl"==b||"rtl"==d&&"ltr"!=b}this.page={y:a.clientY+document.documentElement.scrollTop};this.page.x=window.ie&&9>window.ie?window.ie8?document.__rtlIeFlippedScrollX?a.clientX-document.documentElement.scrollLeft:a.clientX+document.documentElement.scrollLeft:document.__rtlIeFlippedScrollX?a.clientX-(document.documentElement.scrollWidth-
document.documentElement.clientWidth-document.documentElement.scrollLeft):a.clientX+document.documentElement.scrollLeft:a.clientX+document.documentElement.scrollLeft}this.client={x:a.pageX?a.pageX-window.pageXOffset:a.clientX,y:a.pageY?a.pageY-window.pageYOffset:a.clientY};this.rightClick=3==a.which||2==a.button;switch(this.type){case "mouseover":this.relatedTarget=a.relatedTarget||a.fromElement;break;case "mouseout":this.relatedTarget=a.relatedTarget||a.toElement}this.fixRelatedTarget()}return this},
stop:function(){this.event.touches?this.event.preventDefault():this.stopPropagation().preventDefault();return this},stopPropagation:function(){this.event.touches?this.event.preventDefault():this.event.stopPropagation?this.event.stopPropagation():this.event.cancelBubble=!0;return this},preventDefault:function(){this.event.preventDefault||this.event.touches?this.event.preventDefault():this.event.returnValue=!1;return this},fixRelatedTarget:window.Gecko?dgTools.Event.fix.relatedTargetGecko:dgTools.Event.fix.relatedTarget};
(function(){function a(){document.$domOnLoadFired||(d&&window.clearInterval(d),document.$domOnLoadFired=!0,document.isDomLoaded=!0,dgTools.fire(document,"dom:onLoad"))}var d;if(document.addEventListener)window.webkit?(d=window.setInterval(function(){/loaded|complete/.test(document.readyState)&&a()},0),dgTools.observe(window,"load",a,!1)):document.addEventListener("DOMContentLoaded",a,!1);else{document.write("<script id=__onDOMContentLoaded defer src=//:><\/script>");var b=dgTools.$("__onDOMContentLoaded"),
e=function(){"complete"==b.readyState&&(dgTools.unobserve(b,"readystatechange",e),a())};dgTools.observe(b,"readystatechange",e)}})();
(function(){var a=document.createElement("div");a.style.width=a.style.paddingLeft="1px";var d=document.getElementsByTagName("body")[0],b=document.createElement(d?"div":"body");testElementStyle={visibility:"hidden",width:0,height:0,border:0,margin:0,background:"none"};d&&dgTools.extend(testElementStyle,{position:"absolute",left:"-1000px",top:"-1000px"});var e=dgTools.support={};dgTools.extend(b.style,testElementStyle);b.appendChild(a);d=d||document.documentElement;d.insertBefore(b,d.firstChild);e.boxModel=
2===a.offsetWidth;b.innerHTML="";b.style.marginTop="2px";e.cssNameCamelized="2px"==b.style.marginTop&&"2px"!=b.style["margin-top"];d.removeChild(b);input=null})();
(function(){function a(a){for(var b=["transform","WebkitTransform","msTransform","MozTransform","OTransform"],d=0,e=b.length;d<e;d++)if("undefined"!=typeof a.style[b[d]])return q=b[d];return q="transform"}var d=dgTools,b=d.dom,e=["border-left-width","border-right-width","padding-left","padding-right"],h=["border-top-width","border-bottom-width","padding-top","padding-bottom"],n=["padding-left","padding-right"],l=["padding-top","padding-bottom"],q=null,s=function(a,d){var e="";b.css.mapGet&&(d=b.css.mapGet(d));
document.defaultView&&document.defaultView.getComputedStyle?e=document.defaultView.getComputedStyle(a,"").getPropertyValue(d):a.currentStyle&&(d=d.replace(/\-(\w)/g,function(a,b){return b.toUpperCase()}),e=a.currentStyle[d]);null===e&&(e=a.style[d]);""===e&&(e="auto");return e};b.getRenderedStyle=b.css=function(d,r,p){if("string"==typeof r){if("opacity"==r)return b.getOpacity(d,r);if("rotate"==r)return b.getRotate(d,r);"transform"==r&&(r=q||a(d));var k=s(d,r);if(!p&&"auto"==k&&("width"==r||"height"==
r)){var t=d.style.visibility,p=d.style.position,w=d.style.display;d.style.visibility="hidden";d.style.position="absolute";d.style.display="block";var v;"width"==r?v="Width":"height"==r&&(v="Height");k=d["client"+v];(void 0===k||null===k)&&d.document?k=d.document[r]:(k=parseFloat(k),"width"==r?n.iterate(function(a){k-=parseFloat(b.css(d,a))}):"height"==r&&l.iterate(function(a){k-=parseFloat(b.css(d,a))}));if(void 0===k||null===k)if(k=d["offset"+v])k=parseFloat(k),"width"==r?e.iterate(function(a){k-=
parseFloat(b.css(d,a))}):"height"==r&&h.iterate(function(a){k-=parseFloat(b.css(d,a))});d.style.display=w;d.style.position=p;d.style.visibility=t}return k}if("object"==typeof r){if(p){v={};for(t in r)r.hasOwnProperty(t)&&(v["-moz-"+t]=r[t],v["-ms-"+t]=r[t],v["-o-"+t]=r[t],v["-webkit-"+t]=r[t]);r=v}for(t in r)r.hasOwnProperty(t)&&("opacity"==t?b.setOpacity(d,r[t]):"rotate"==t?b.setRotate(d,r[t]):(v=t,"float"==v?v=window.ie?"styleFloat":"cssFloat":"transform"==v?v=q||a(d):b.css.mapSet&&(v=b.css.mapSet(v)),
d.style[v]=r[t]))}return d};b.setOpacity=function(a,d,e){d=parseFloat(d);d=1E-5>d?0:d;if(window.ie&&9>window.ie)if(a.style.zoom=1,a.style.filter=b.css(a,"filter"),1<=d&&!e&&a.style.filter.match(/alpha\(\s*opacity\s*=\s*(.*)\s*\)/)){var h=a.style.filter.replace(/alpha\([^\)]*\)/gi,"").trim(),l=document.createElement("div");a.style.filter=l.style.filter;0<h.length&&(a.style.filter=h)}else h=a.style.filter.replace(/alpha\([^\)]*\)/gi,"").trim(),1!=d&&(h+=(0<h.length?" ":"")+("alpha(opacity="+100*d+")")),
a.style.filter=h;1==d&&!e&&(d="");a.style.opacity=d;a.style.MozOpacity=d;a.style.KhtmlOpacity=d;""===d&&0==b.getOpacity(a)&&b.setOpacity(a,1,!0);return a};b.getOpacity=function(a){var b=s(a,"opacity");null==b&&(b=s(a,"-moz-opacity"));null==b&&(b=s(a,"-khtml-opacity"));return null==b&&window.ie&&9>window.ie&&(a=s(a,"filter"))&&(a=a.match(/alpha\(opacity=(.*)\)/))&&a[1]?parseFloat(a[1])/100:b=null==b?1:parseFloat(b)};b.setRotate=function(a,d){var e=b.css(a,"transform")||"none",h=d.toString().match(/^(-?\d+(\.\d+)?)(.+)?$/);
if(h){var l="deg";h[3]&&(l=h[3]);b.css(a,{transform:e.replace(/none|rotate\([^)]*\)/,"")+"rotate("+h[1]+l+")"})}return a};b.getRotate=function(a){return(a=(b.css(a,"transform")||"none").match(/rotate\(([^)]+)\)/))&&a[1]?a[1]:0};var p=null,t=["khtml","ms","o","moz","webkit"],w=t.length;b.cssSupported=function(a){p||(p=document.createElement("div"));a=a.toLowerCase();if(a in p.style||a.camelize()in p.style)return!0;for(var b=w,d;b--;)if(d=t[b]+a,d in p.style||d.camelize()in p.style)return!0;return!1};
d.support.cssNameCamelized&&!window.Firefox&&(b.css.mapGet=function(a){return"-"==a.charAt(0)?a:a.camelize()});d.support.cssNameCamelized&&(b.css.mapSet=function(a){return"-"==a.charAt(0)?a:a.camelize()})})();
(function(){var a=dgTools;a.Color=Class.extend({init:function(d){if(d instanceof a.Color)this.red=d.red,this.green=d.green,this.blue=d.blue,this.alpha=d.alpha;else if(3==arguments.length||4==arguments.length)this.red=parseInt(arguments[0],10)||0,this.green=parseInt(arguments[1],10)||0,this.blue=parseInt(arguments[2],10)||0,this.alpha=parseFloat(arguments[3])||1;else if("string"==typeof d)if(d=d.trim(),"rgba("==d.substr(0,5)){var d=d.replace(/^[rgba\(\) ;]*|[rgba\(\) ;]*$/g,""),b=d.split(",");4==b.length?
(this.red=parseInt(b[0].trim(),10),this.green=parseInt(b[1].trim(),10),this.blue=parseInt(b[2].trim(),10),this.alpha=parseFloat(b[3].trim())):this.red=this.green=this.blue=this.alpha=-1}else if("rgb("==d.substr(0,4))d=d.replace(/^[rgba\(\) ;]*|[rgba\(\) ;]*$/g,""),b=d.split(","),3==b.length?(this.red=parseInt(b[0].trim(),10),this.green=parseInt(b[1].trim(),10),this.blue=parseInt(b[2].trim(),10),this.alpha=1):this.red=this.green=this.blue=this.alpha=-1;else{if("transparent"==d)return a.Color.Transparent;
d=d.replace(/^[# ;]*|[# ;]*$/g,"");3==d.length&&(d=d.substr(0,1)+d.substr(0,1)+d.substr(1,1)+d.substr(1,1)+d.substr(2,1)+d.substr(2,1));6!=d.length?this.red=this.green=this.blue=this.alpha=-1:(this.red=parseInt(d.substr(0,2),16),this.green=parseInt(d.substr(2,2),16),this.blue=parseInt(d.substr(4,2),16),this.alpha=1)}else d instanceof Object?(this.red=parseInt(d.red,10),this.green=parseInt(d.green,10),this.blue=parseInt(d.blue,10),this.alpha=parseFloat(d.alpha)):(this.blue=this.green=this.red=0,this.alpha=
1);1<this.alpha?this.alpha=1:-1>this.alpha&&(this.alpha=-1);255<this.red?this.red=255:-1>this.red&&(this.red=-1);255<this.green?this.green=255:-1>this.green&&(this.green=-1);255<this.blue?this.blue=255:-1>this.blue&&(this.blue=-1)},css:function(){return 1==this.alpha?this.cssHash():this.cssRgba()},cssHash:function(){return 0==this.alpha?"transparent":0>this.red||0>this.green||0>this.blue||0>this.alpha?"":"#"+this.red.toPaddedString(2,16)+this.green.toPaddedString(2,16)+this.blue.toPaddedString(2,
16)},cssRgb:function(){return 0==this.alpha?"transparent":0>this.red||0>this.green||0>this.blue||0>this.alpha?"":"rgb("+this.red+","+this.green+","+this.blue+")"},cssRgba:function(){return 0==this.alpha?"transparent":0>this.red||0>this.green||0>this.blue||0>this.alpha?"":"rgba("+this.red+","+this.green+","+this.blue+","+this.alpha+")"},toString:function(){return this.css()},isEmpty:function(){return 0>this.red||0>this.green||0>this.blue||0>this.alpha},isTransparent:function(){return 0==this.alpha},
valueOf:function(){return 0>this.red||0>this.green||0>this.blue||0>this.alpha?-1:this.blue+(this.green<<8)+(this.red<<16)+16777216*parseInt(255*this.alpha,10)},colorByTranslatingColor:function(d,b){return new a.Color({red:(d.red-this.red)*b+this.red,green:(d.green-this.green)*b+this.green,blue:(d.blue-this.blue)*b+this.blue,alpha:(d.alpha-this.alpha)*b+this.alpha})}});a.Color.fromArgb=function(){return 3==arguments.length?new a.Color({red:arguments[0],green:arguments[1],blue:arguments[2],alpha:1}):
4==arguments.length?new a.Color({alpha:arguments[0],red:arguments[1],green:arguments[2],blue:arguments[3]}):new a.Color};a.Color.fromRgb=a.Color.fromRgba=function(){return 3==arguments.length?new a.Color({red:arguments[0],green:arguments[1],blue:arguments[2],alpha:1}):4==arguments.length?new a.Color({red:arguments[0],green:arguments[1],blue:arguments[2],alpha:arguments[3]}):new a.Color};a.Color.Empty=new a.Color(-1,-1,-1,-1);a.Color.Transparent=new a.Color(255,255,255,0);a.Color.interpolateColors=
function(d,b,e){if(0==d.length)return null;if(1==d.length)return new a.Color(d[0]);0>e?e=0:1<e&&(e=1);var h;if(null==b){b=[];h=1/(d.length-1);for(var n=0;n<d.length;n++)b.push(h*n)}for(n=0;n<b.length;n++)if(h=b[n],0>h?h=b[n]=0:1<h&&(h=b[n]=1),0<n&&h<b[n-1]&&(h=b[n]=b[n-1]),h>=e){if(0==n)return new a.Color(d[0]);h=d[n-1];d=d[n];h instanceof a.Color||(h=new a.Color(h));d instanceof a.Color||(d=new a.Color(d));return h.colorByTranslatingColor(d,(e-b[n-1])/(b[n]-b[n-1]))}return new a.Color(d[d.length-
1])}})();
(function(){function a(){return!1}function d(b,d,e){if(d&&0>=b.__imageDraggingEnabler&&!e)return!0;b.__imageDraggingEnabler||(b.__imageDraggingEnabler=0);b.__imageDraggingEnabler+=d?-1:1;return d&&(0==b.__imageDraggingEnabler||e)?(b.detachEvent&&b.detachEvent("ondragstart",a),b.__imageDraggingEnabler=0,!0):!d&&1==b.__imageDraggingEnabler?(b.attachEvent&&b.attachEvent("ondragstart",a),!1):0==b.__imageDraggingEnabler}function b(b,d){if(b&&0>=e&&!d)return!0;e+=b?-1:1;return b&&(0==e||d)?(dgTools.unobserve(document,"selectstart",
a),document.unselectable="off",dgTools.dom.css(document.body,{"-moz-user-select":""}),e=0,!0):!b&&1==e?(dgTools.observe(document,"selectstart",a),document.unselectable="on",dgTools.dom.css(document.body,{"-moz-user-select":"none"}),!1):0==e}var e=0;dgTools.dom.enableImageDragging=function(){d.apply(this,arguments)};dgTools.dom.enableTextSelect=function(){b.apply(this,arguments)}})();
(function(){dgTools.select=function(){function a(a){E.test(a)&&(a=" "+a);return a.match(y)||[]}function d(a,b,d){function e(b){b=d==w?h.length-b:b-1;return h[b]==a}switch(b){case "n":return!0;case "even":b="2n";break;case "odd":b="2n+1"}var h=g(a.parentNode);if(!isNaN(b))return e(b);var b=b.split("n"),k=parseInt(b[0]),b=parseInt(b[1]);if((isNaN(k)||1==k)&&0==b)return!0;if(0==k&&!isNaN(b))return e(b);isNaN(b)&&(b=0);for(var l=1;a=d(a);)l++;return isNaN(k)||1==k?d==w?l<=b:b>=l:l%k==b}var b=/\s*,\s*/,
e=function(d,g){try{var k=[],l=arguments.callee.caching&&!g,p=g?g.constructor==Array?g:[g]:[document],t=q.parse(d).replace(F,"$1").replace(x,"$1*$2").split(b),w;for(w=0;w<t.length;w++){d=a(t[w]);if(r&&" *#"==d.slice(0,3).join("")){for(var d=d.slice(2),s=[],u=p,y=d[1],v=void 0,A=void 0,B=void 0,A=0;A<u.length;A++)if(v=u[A].all.item(y))if(v.id==y)s.push(v);else if(null!=v.length)for(B=0;B<v.length;B++)v[B].id==y&&s.push(v[B]);g=s}else g=p;for(var s=0,C,D,G,u="";s<d.length;){C=d[s++];D=d[s++];u+=C+D;
G="";if("("==d[s]){for(;")"!=d[s++]&&s<d.length;)G+=d[s];G=G.slice(0,-1);u+="("+G+")"}var E;if(l&&h[u])E=h[u];else{var v=g,A=C,B=D,M=G;J.test(B)&&(B=B.split(J),M=B[0],B=B[1]);var N=[];if(n[A])n[A](N,v,B,M);E=N}g=E;l&&(h[u]=g)}k=k.concat(g)}delete e.error;return k}catch(O){return e.error=O,[]}};e.toString=function(){return"function cssQuery() {\n  [version 2.0.2]\n}"};var h={};e.caching=!1;e.clearCache=function(b){b?(b=a(b).join(""),delete h[b]):h={}};e.valueOf=function(a){return a?eval(a):this};var n=
{},l={},q={match:/\[([\w-]+(\|[\w-]+)?)\s*(\W?=)?\s*([^\]]*)\]/},s=[];n[" "]=function(a,b,d,e){var g,h,l;for(h=0;h<b.length;h++){var n=k(b[h],d,e);for(l=0;g=n[l];l++)p(g)&&A(g,e)&&a.push(g)}};n["#"]=function(a,b,d){var e,g;for(g=0;e=b[g];g++)e.id==d&&a.push(e)};n["."]=function(a,b,d){var d=RegExp("(^|\\s)"+d+"(\\s|$)"),e,g;for(g=0;e=b[g];g++)d.test(e.className)&&a.push(e)};n[":"]=function(a,b,d,e){var d=l[d],g,h;if(d)for(h=0;g=b[h];h++)d(g,e)&&a.push(g)};n["~"]=function(a,b,d,e){var g,h;for(h=0;g=
b[h];h++)for(;g=w(g);)v(g,d,e)&&a.push(g)};n[">"]=function(a,b,d,e){var h,k,l;for(k=0;k<b.length;k++){var p=g(b[k]);for(l=0;h=p[l];l++)v(h,d,e)&&a.push(h)}};n["+"]=function(a,b,d,e){for(var g=0;g<b.length;g++){var h=w(b[g]);h&&v(h,d,e)&&a.push(h)}};n["@"]=function(a,b,d){var d=s[d].test,e,g;for(g=0;e=b[g];g++)d(e)&&a.push(e)};l.link=function(a){var b=a.ownerDocument||a.document;if(b.links)for(var d=0;d<b.links.length;d++)if(b.links[d]==a)return!0};l.visited=function(){};l.contains=function(a,b){b=
RegExp(D.remove(b).regexEscape());return b.test(u(a))};l.root=function(a){return a==(a.ownerDocument||a.document).documentElement};l.empty=function(a){var b,d;for(d=0;b=a.childNodes[d];d++)if(p(b)||3==b.nodeType)return!1;return!0};l["last-child"]=function(a){return!w(a)};l["only-child"]=function(a){a=a.parentNode;return(p(a.firstChild)||w(a.firstChild))==(p(a.lastChild)||t(a.lastChild))};l.not=function(a,b){for(var d=e(b,a.ownerDocument||a.document),g=0;g<d.length;g++)if(d[g]==a)return!1;return!0};
l["nth-child"]=function(a,b){return d(a,b,t)};l["nth-last-child"]=function(a,b){return d(a,b,w)};l.target=function(a){return a.id==location.hash.slice(1)};l.checked=function(a){return a.checked};l.enabled=function(a){return!1===a.disabled};l.disabled=function(a){return a.disabled};l.indeterminate=function(a){return a.indeterminate};l["first-child"]=function(a){return!t(a)};l.lang=function(a,b){for(b=RegExp("^"+b,"i");a&&!a.getAttribute("lang");)a=a.parentNode;return a&&b.test(a.getAttribute("lang"))};
var p=function(a){return a&&1==a.nodeType&&"!"!=a.tagName?a:null},t=function(a){for(;a&&(a=a.previousSibling)&&!p(a););return a},w=function(a){for(;a&&(a=a.nextSibling)&&!p(a););return a},g=function(a){for(var b=[],a=p(a.firstChild)||w(a.firstChild);a;)b.push(a),a=w(a);return b},r=eval("false;/*@cc_on@if(@_win32)isMSIE=true@end@*/"),G,k,A,u,v=function(a,b,d){if("*"==b)return p(a);if(!A(a,d))return!1;G(a)||(b=b.toUpperCase());return a.tagName==b};if(r)G=function(a){a=a.ownerDocument||a.document;return"unknown"==
typeof a.mimeType?/\.xml$/i.test(a.URL):Boolean("XML Document"==a.mimeType)},k=function(a,b){return"*"==b&&a.all?a.all:a.getElementsByTagName(b)},A=function(a,b){return!b||"*"==b||a.scopeName==b},u=function(a){return a.innerText};else{G=document.contentType?function(a){return/xml/i.test((a.ownerDocument||a.document).contentType)}:function(a){return"HTML"!=(a.ownerDocument||a.document).documentElement.tagName};k=function(a,b,d){return d?a.getElementsByTagNameNS("*",b):a.getElementsByTagName(b)};A=
function(a,b){return!b||"*"==b||a.prefix==b};u=function(a){return a.textContent||a.innerText||C(a)};var C=function(a){var b="",d,e;for(e=0;d=a.childNodes[e];e++)switch(d.nodeType){case 11:case 1:b+=C(d);break;case 3:b+=d.nodeValue}return b}}[].push||(Array.prototype.push=function(){for(var a=0;a<arguments.length;a++)this[this.length]=arguments[a];return this.length});var J=/\|/,E=/^[^\s>+~]/,y=/[\s#.:>+~()@]|[^\s#.:>+~()@]+/g,F=/\s*([\s>+~(),]|^|$)\s*/g,x=/([\s>+~,]|[^(]\+|^)([#.:@])/g,D={toString:function(){return"'"},
match:/^('[^']*')|("[^"]*")$/,test:function(a){return this.match.test(a)},add:function(a){return this.test(a)?a:this+a+this},remove:function(a){return this.test(a)?a.slice(1,-1):a}};q.NS_IE=/\\:/g;q.PREFIX="@";q.tests={};q.replace=function(a,b,d,e,g){a=this.PREFIX+a;s[a]||(b=this.create(b,e||"",g||""),s[a]=b,s.push(b));return s[a].id};q.parse=function(a){for(var a=a.replace(this.NS_IE,"|"),b;b=a.match(this.match);)b=this.replace(b[0],b[1],b[2],b[3],b[4]),a=a.replace(this.match,b);return a};q.create=
function(a,b,d){var e={};e.id=this.PREFIX+s.length;e.name=a;b=(b=this.tests[b])?b(this.getAttribute(a),D.remove(d)):!1;e.test=new Function("e","return "+b);return e};q.getAttribute=function(a){switch(a.toLowerCase()){case "id":return"e.id";case "class":return"e.className";case "for":return"e.htmlFor";case "href":if(r)return"String((e.outerHTML.match(/href=\\x22?([^\\s\\x22]*)\\x22?/)||[])[1]||'')"}return"e.getAttribute('"+a.replace(J,":")+"')"};q.tests["^="]=function(a,b){return"/^"+b.regexEscape()+
"/.test("+a+")"};q.tests["$="]=function(a,b){return"/"+b.regexEscape()+"$/.test("+a+")"};q.tests["*="]=function(a,b){return"/"+b.regexEscape()+"/.test("+a+")"};q.tests[""]=function(a){return a};q.tests["="]=function(a,b){return a+"=="+D.add(b)};q.tests["~="]=function(a,b){return"/(^| )"+b.regexEscape()+"( |$)/.test("+a+")"};q.tests["|="]=function(a,b){return"/^"+b.regexEscape()+"(-|$)/.test("+a+")"};return e}()})();
(function(){var a={_keyStr:"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=",encode:function(d){for(var b="",e,h,n,l,q,s,p=0,d=a._utf8_encode(d);p<d.length;)e=d.charCodeAt(p++),h=d.charCodeAt(p++),n=d.charCodeAt(p++),l=e>>2,e=(e&3)<<4|h>>4,q=(h&15)<<2|n>>6,s=n&63,isNaN(h)?q=s=64:isNaN(n)&&(s=64),b=b+this._keyStr.charAt(l)+this._keyStr.charAt(e)+this._keyStr.charAt(q)+this._keyStr.charAt(s);return b},decode:function(d){for(var b="",e,h,n,l,q,s=0,d=d.replace(/[^A-Za-z0-9\+\/\=]/g,
"");s<d.length;)e=this._keyStr.indexOf(d.charAt(s++)),h=this._keyStr.indexOf(d.charAt(s++)),l=this._keyStr.indexOf(d.charAt(s++)),q=this._keyStr.indexOf(d.charAt(s++)),e=e<<2|h>>4,h=(h&15)<<4|l>>2,n=(l&3)<<6|q,b+=String.fromCharCode(e),64!=l&&(b+=String.fromCharCode(h)),64!=q&&(b+=String.fromCharCode(n));return b=a._utf8_decode(b)},_utf8_encode:function(a){for(var a=a.replace(/\r\n/g,"\n"),b="",e=0;e<a.length;e++){var h=a.charCodeAt(e);128>h?b+=String.fromCharCode(h):(127<h&&2048>h?b+=String.fromCharCode(h>>
6|192):(b+=String.fromCharCode(h>>12|224),b+=String.fromCharCode(h>>6&63|128)),b+=String.fromCharCode(h&63|128))}return b},_utf8_decode:function(a){for(var b="",e=0,h=c1=c2=0;e<a.length;)h=a.charCodeAt(e),128>h?(b+=String.fromCharCode(h),e++):191<h&&224>h?(c2=a.charCodeAt(e+1),b+=String.fromCharCode((h&31)<<6|c2&63),e+=2):(c2=a.charCodeAt(e+1),c3=a.charCodeAt(e+2),b+=String.fromCharCode((h&15)<<12|(c2&63)<<6|c3&63),e+=3);return b}};dgTools.Base64=a})();ajax.layout=dgTools.Elm=dgTools.dom;
ajax.browser=dgTools.Browser;ajax.tables=dgTools.Table;ajax.cookies=dgTools.Cookies;ajax.events={register:dgTools.observe,unregister:dgTools.unobserve,fire:dgTools.fire,Event:dgTools.Event};ajax.findScriptPath=dgTools.Io.findScriptPath;ajax.getFileName=dgTools.Io.getFileName;var JSON;JSON||(JSON={});
(function(){function a(a){return 10>a?"0"+a:a}function d(a){h.lastIndex=0;return h.test(a)?'"'+a.replace(h,function(a){var b=q[a];return"string"===typeof b?b:"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+a+'"'}function b(a,e){var h,g,r,q,k=n,A,u=e[a];u&&("object"===typeof u&&"function"===typeof u.toJSON)&&(u=u.toJSON(a));"function"===typeof s&&(u=s.call(e,a,u));switch(typeof u){case "string":return d(u);case "number":return isFinite(u)?String(u):"null";case "boolean":case "null":return String(u);
case "object":if(!u)return"null";n+=l;A=[];if("[object Array]"===Object.prototype.toString.apply(u)){q=u.length;for(h=0;h<q;h+=1)A[h]=b(h,u)||"null";r=0===A.length?"[]":n?"[\n"+n+A.join(",\n"+n)+"\n"+k+"]":"["+A.join(",")+"]";n=k;return r}if(s&&"object"===typeof s){q=s.length;for(h=0;h<q;h+=1)g=s[h],"string"===typeof g&&(r=b(g,u))&&A.push(d(g)+(n?": ":":")+r)}else for(g in u)Object.prototype.hasOwnProperty.call(u,g)&&(r=b(g,u))&&A.push(d(g)+(n?": ":":")+r);r=0===A.length?"{}":n?"{\n"+n+A.join(",\n"+
n)+"\n"+k+"}":"{"+A.join(",")+"}";n=k;return r}}"function"!==typeof Date.prototype.toJSON&&(Date.prototype.toJSON=function(){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+a(this.getUTCMonth()+1)+"-"+a(this.getUTCDate())+"T"+a(this.getUTCHours())+":"+a(this.getUTCMinutes())+":"+a(this.getUTCSeconds())+"Z":null},String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(){return this.valueOf()});var e=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,
h=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,n,l,q={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},s;"function"!==typeof JSON.stringify&&(JSON.stringify=function(a,d,e){var g;l=n="";if("number"===typeof e)for(g=0;g<e;g+=1)l+=" ";else"string"===typeof e&&(l=e);if((s=d)&&"function"!==typeof d&&("object"!==typeof d||"number"!==typeof d.length))throw Error("JSON.stringify");return b("",{"":a})});
"function"!==typeof JSON.parse&&(JSON.parse=function(a,b){function d(a,e){var g,h,l=a[e];if(l&&"object"===typeof l)for(g in l)Object.prototype.hasOwnProperty.call(l,g)&&(h=d(l,g),void 0!==h?l[g]=h:delete l[g]);return b.call(a,e,l)}var g,a=String(a);e.lastIndex=0;e.test(a)&&(a=a.replace(e,function(a){return"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)}));if(/^[\],:{}\s]*$/.test(a.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,
"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"")))return g=eval("("+a+")"),"function"===typeof b?d({"":g},""):g;throw new SyntaxError("JSON.parse");})})();
