/* Daniel Cohen Gindi (danielgindi@gmail.com) 054-5655765 */
/* Version: 2013-01-16 */
/* Depends on dgTools.js */
(function(){var b=dgTools,e=b.dom,d={options:{enabled:!0,opacity:1,delay:0,fadeInDuration:250,fadeOutDuration:250,forceZoomKey:-1},init:function(a){this.options=b.extend(this.options,a||{});this.tooltip=new d.Tip(this.options);this.currentImg=null;this.mouseDown=!1;b.observe(document.body,"drag",this.onMouseDrag.bind(this));b.observe(document.body,"dragstart",this.onMouseDown.bind(this));b.observe(document.body,"dragend",this.onMouseUp.bind(this));b.observe(document.body,"mousedown",this.onMouseDown.bind(this));
b.observe(document.body,"mouseup",this.onMouseUp.bind(this));b.observe(document.body,"mousemove",this.onMouseMove.bind(this));b.observe(document.body,"mousewheel",this.onMouseMove.bind(this));b.observe(document.body,"keydown",this.onKeyDown.bind(this));b.observe(document.body,"keyup",this.onKeyUp.bind(this));b.observe(document.body,"click",this.onBodyClick.bind(this))},setOptions:function(a){this.options=b.extend(this.options,a);this.tooltip.setOptions(a)},toggle:function(){this.options.enabled=!this.options.enabled;
this.options.enabled||this.tooltip.hide()},hideTooltip:function(){if(this.tooltip.open&&!this.tooltip.hiding||null!==this.currentImg)this.tooltip.hide(),this.currentImg=null},onKeyDown:function(a){a=a||event;a.keyCode==this.options.forceZoomKey&&(this.override=!0)},onKeyUp:function(a){a=a||event;a.keyCode==this.options.forceZoomKey&&(this.override=!1,this.options.enabled||this.tooltip.hide())},onMouseDrag:function(){this.hideTooltip()},onMouseDown:function(a){a=a||event;this.mouseDown=!0;this.mouseDownCoords=
{x:a.pageX||a.clientX+document.documentElement.scrollLeft,y:a.pageY||a.clientY+document.documentElement.scrollTop}},onMouseUp:function(){this.mouseDown=!1;this.mouseDownCoords=null},onBodyClick:function(){this.hideTooltip()},onMouseMove:function(a){a=a||event;if(this.mouseDown){var c=a.pageY||a.clientY+document.documentElement.scrollTop;(5<Math.abs((a.pageX||a.clientX+document.documentElement.scrollLeft)-this.mouseDownCoords.x)||5<Math.abs(c-this.mouseDownCoords.y))&&this.hideTooltip()}else if(a=
a.target||a.srcElement,3==a.nodeType&&(a=a.parentNode),c=null,"IMG"==a.tagName&&a.className&&/dgImageHover/.test(a.className)||a.parentNode.className&&/dgImageHover/.test(a.parentNode.className)?c=a.getAttribute("data-src")||a.parentNode.href:"A"==a.tagName&&(a.className&&/dgImageHover/.test(a.className))&&(c=a.href),(this.options.enabled||this.override)&&c){if(!this.currentImg||this.currentImg!==c)this.currentImg=c,this.tooltip.start(this.currentImg)}else this.hideTooltip()}};d.Tip=Class.extend({options:{padding:5,
offset:10,gutter:20,opacity:1,delay:0,fadeInDuration:250,fadeOutDuration:250},init:function(a){var c=dgTools.Io.findScriptPath("dgImageHover.js",!0)||dgTools.Io.findScriptPath("dgImageHover_src.js",!0);this.options=b.extend(this.options,a);this.tooltip=document.body.appendChild(e.build("div",{css:{position:"absolute","font-size":0,"z-index":99999,"-moz-box-shadow":"0px 0px 10px rgba(0,0,0,1)","-webkit-box-shadow":"0px 0px 10px rgba(0,0,0,1)","box-shadow":"0px 0px 10px rgba(0,0,0,1);","min-height":"50px",
"min-width":"50px","pointer-events":"none",background:"#fff url("+(c+"loading.gif").replace("'","\\'")+") no-repeat center center",overflow:"hidden",display:"none",opacity:0,padding:this.options.padding+"px"}}));this.tooltipImg=null;this.currentSrc="";this.hiding=this.opening=this.open=!1;this.coords=null},setOptions:function(a){this.options=b.extend(this.options,a)},setPosition:function(){var a,c,b=this.coords,f,g="auto",h=document.body.scrollLeft,i=document.body.scrollTop,d=!1,j;if((this.open||
this.opening)&&b)f=b.y+i-this.tooltip.offsetHeight/2,g=b.x+h+this.options.offset,this.tooltipImg&&this.tooltipImg._loaded&&(a=document.body.clientWidth,c=this.tooltipImg.naturalWidth,(j=b.x+this.options.offset+(c+2*this.options.padding)<a-this.options.gutter)||(d=b.x-this.options.offset-(c+2*this.options.padding)>this.options.gutter),(j||d)&&e.css(this.tooltipImg,{width:"auto",height:"auto"}),!j&&d?g=b.x+h-this.options.offset-(c+2*this.options.padding):!j&&!d&&(b.x<=a/2?e.css(this.tooltipImg,{width:a-
(b.x+this.options.offset+2*this.options.padding+this.options.gutter)+"px",height:"auto"}):(g=h+this.options.gutter,e.css(this.tooltipImg,{width:b.x-this.options.offset-2*this.options.padding-this.options.gutter+"px",height:"auto"}))),f>window.innerHeight+i-this.tooltip.offsetHeight-this.options.gutter&&(f=window.innerHeight+i-this.tooltip.offsetHeight-this.options.gutter),f<i+this.options.gutter&&(f=i+this.options.gutter,this.tooltip.offsetHeight>window.innerHeight-2*this.options.gutter&&(e.css(this.tooltipImg,
{height:window.innerHeight-2*this.options.padding-2*this.options.gutter+"px",width:"auto"}),g=(j=b.x+this.options.offset+this.tooltip.offsetWidth<a-this.options.gutter)?b.x+h+this.options.offset:b.x+h-this.tooltip.offsetWidth-this.options.offset))),e.css(this.tooltip,{top:parseInt(f,10)+"px",left:parseInt(g,10)+"px"})},onMouseMove:function(a){a=a||target;this.coords={x:a.pageX?a.pageX-window.pageXOffset:a.clientX,y:a.pageY?a.pageY-window.pageYOffset:a.clientY};(this.open||this.opening)&&this.setPosition()},
start:function(a){this.resetImg();this.opening=!0;this.setImg(a);this.show();this._fMouseMove||(this._fMouseMove=b.observe(document.body,"mousemove",this.onMouseMove.bind(this)))},resetImg:function(){var a=this;a.currentSrc="";a.tooltipImg=null;setTimeout(function(){a.setPosition()},0)},setImg:function(a){var c=this;this.currentSrc=a;c.tooltip.firstChild&&c.tooltip.removeChild(c.tooltip.firstChild);this.tooltipImg=b.ajax.loadImage(a,function(a,b){if(a){if((c.open||c.opening)&&b==c.currentSrc)c.tooltipImg._loaded=
!0,c.tooltipImg.naturalWidth=c.tooltipImg.width,c.tooltipImg.naturalHeight=c.tooltipImg.height,setTimeout(function(){c.tooltip.appendChild(c.tooltipImg);c.setPosition()},0)}else c.hide()})},show:function(){var a=this;a.showInterval&&(clearInterval(a.showInterval),a.showInterval=null);a.showAnim&&(a.showAnim.stop(),a.showAnim=null);a.hideAnim&&(a.hideAnim.stop(),a.hideAnim=null,a.open=!1);a.opening=!0;a.setPosition();a.hiding=!1;a.showInterval=setTimeout(function(){a.open=!0;a.opening=!1;a.setPosition();
e.show(a.tooltip);var c=a.showAnim=b.animate(a.tooltip,{to:{opacity:a.options.opacity},duration:a.options.fadeInDuration,fps:70,complete:function(){a.showAnim==c&&(a.showAnim=null)}})},a.open?0:a.options.delay)},hide:function(){var a=this;a.showInterval&&(clearInterval(a.showInterval),a.showInterval=null);a.showAnim&&(a.showAnim.stop(),a.showAnim=null);a.hideAnim&&(a.hideAnim.stop(),a.hideAnim=null);a.hiding=!0;a.opening=!1;var c=a.hideAnim=b.animate(a.tooltip,{to:{opacity:0},duration:a.options.fadeOutDuration,
fps:70,complete:function(){a.hideAnim==c&&(a.hideAnim=null);e.hide(a.tooltip);if(a.onHidden)a.onHidden();b.unobserve(document.body,"mousemove",a._fMouseMove);a._fMouseMove=null}})},onHidden:function(){this.hiding=this.opening=this.open=!1;this.resetImg()}});window.dgImageHover=d;b.observe(document,"dom:onLoad",function(){d.init()})})();
