/* Javascript by Daniel Cohen Gindi (c) danielgindi@gmail.com 054-5655765 */
/* Copyright: Daniel Cohen Gindi */
/* Version: 2010-07-08 */
var Sortable=function(a){this.element=Sortable.$(a.elementId||null);this.byTag=((a.byTag||"li")+"").toUpperCase();this.byClassName=a.byClassName||null;this.handleByTag=((a.handleByTag||"")+"").toUpperCase();this.handleByClassName=a.handleByClassName||null;this.treshold=parseInt(a.treshold,10)||4;this.autoDump=a.autoDump||null;this.constrain=a.constrain||null;this.rtl=!!a.rtl||!1;this.transparent=!1===a.transparent?!1:!0;this.classWhenDragging=a.classWhenDragging||null;this.classAfterDragged=a.classAfterDragged||
null;this.sortableItemFunc=a.itemFunc||null;var b=this;this.Func_onDragStart=function(){b._onDragStart.apply(b,arguments)};this.Func_onDragMove=function(){b._onDragMove.apply(b,arguments)};this.Func_onDragEnd=function(){b._onDragEnd.apply(b,arguments)};null!=this.element&&(this._create(),a.init&&(this.makeSortable(),a.dumpNow&&this.autoDump&&(Sortable.$(this.autoDump).value=Sortable.Dumper.serialize(this))));return this};
Sortable.$=function(a){return!a||a&&1==a.nodeType?a:document.getElementById?document.getElementById(a):document.layers?document.layers[a]:document.all[a]};
Sortable.prototype={element:null,byTag:null,byClassName:null,isTableMode:!1,treshold:4,list:null,wasDraggedBefore:!1,transparent:!0,classWhenDragging:null,IE8BUGFIX:!1,_create:function(){this.reinit()},reinit:function(){for(var a=Sortable.utility.findChildren(this.element,this.byTag,this.byClassName),b=0,c=a.length;b<c;b++)a[b].getAttribute("locksort")?(a.splice(b,1),b--):""==this.handleByTag&&(null==this.handleByClassName||""==this.handleByClassName)?a[b]._handle=a[b]:(a[b]._handle=Sortable.utility.findChild(a[b],
this.handleByTag,this.handleByClassName),a[b]._handle||(a[b]._handle=a[b]));0<a.length&&"TR"==a[0].tagName&&(this.isTableMode=!0);this.list=a;this.isTableMode&&(window.ActiveXObject&&navigator.appVersion.indexOf("MSIE 8.0"))&&(this.IE8BUGFIX=!0)},makeSortable:function(){var a=this.sortableItemFunc,b=null,c=this.autoDump||null,d=this;c&&(b="string"==typeof c?function(){Sortable.$(c).value=Sortable.Dumper.serialize(d)}:function(){c.value=Sortable.Dumper.serialize(d)});var e=null;"horizontal"==this.constrain?
e=Sortable.Constraints.horizontal():"vertical"==this.constrain?e=Sortable.Constraints.vertical():this.constrain&&(this.constrain.length&&4==this.constrain.length)&&(e=Sortable.Constraints.region(this.constrain[0],this.constrain[1],this.constrain[2],this.constrain[3]));Sortable.utility.map(this.list,function(a){if(!a._sortable){a._sortable=!0;a=new Sortable.Group(a,a._handle,d);a.register("dragstart",d.Func_onDragStart);a.register("dragmove",d.Func_onDragMove);a.register("dragend",d.Func_onDragEnd);
a.setThreshold(d.treshold);var c,f;a.addTransform(function(a){return a.constrainTo(c,f)});a.register("dragstart",function(){var a=d.list;c=f=Sortable.Coordinates.topLeftOffset(a[0]);for(var b=1,e=a.length;b<e;b++){var g=Sortable.Coordinates.topLeftOffset(a[b]);c=c.min(g);f=f.max(g)}});b&&a.register("dragend",b);e&&a.addTransform(e);d.isTableMode&&"vertical"!=this.constrain&&a.lockToVertical()}});if(a)for(var f=1,g=arguments.length;f<g;f++)Sortable.utility.map(items,a)},restoreOrder:function(){if(this.wasDraggedBefore)for(var a=
0<this.list.length?this.list[0].parentNode:null,b=0,c=this.originalList.length;b<c;b++)a.removeChild(this.originalList[b]),a.insertBefore(this.originalList[b],null)},_onDragStart:function(){if(!this.wasDraggedBefore){this.wasDraggedBefore=!0;this.originalList=[];for(var a=0,b=this.list.length;a<b;a++)this.originalList[a]=this.list[a]}},_onDragMove:function(a){for(var b=a.group.element,c=a.transformedMouseOffset,d=null,e=Sortable.utility.previousItem(b,b.nodeName);null!=e;){var f=Sortable.Coordinates.topLeftOffset(e),
g=Sortable.Coordinates.bottomRightOffset(e);if(this.rtl&&c.y<=g.y&&c.x>=f.x||!this.rtl&&c.y<=g.y&&c.x<=g.x)d=e;e=Sortable.utility.previousItem(e,b.nodeName)}if(null!=d)Sortable.utility.moveBefore(a.group.Sortable.list,b,d,this.IE8BUGFIX);else{for(e=Sortable.utility.nextItem(b,b.nodeName);null!=e;){f=Sortable.Coordinates.topLeftOffset(e);g=Sortable.Coordinates.bottomRightOffset(e);if(this.rtl&&f.y<=c.y&&g.x>=c.x||!this.rtl&&f.y<=c.y&&f.x<=c.x)d=e;e=Sortable.utility.nextItem(e,b.nodeName)}null!=d&&
Sortable.utility.moveBefore(a.group.Sortable.list,b,Sortable.utility.nextItem(d,b.nodeName),this.IE8BUGFIX)}},_onDragEnd:function(a){this.isTableMode||(new Sortable.Coordinate(0,0)).reposition(a.group.element)}};
Sortable.Group=function(a,b,c){b=b||a;this.Sortable=c;this.element=a;this._handle=b;this._thresholdDistance=0;this._listeners=[];this._listeners.draginit=[];this._listeners.dragstart=[];this._listeners.dragmove=[];this._listeners.dragend=[];this._transforms=[];this.Sortable.isTableMode||(c=Sortable.utility.readCssStyle(a,"position"),"static"==c?a.style.position="relative":"absolute"==c&&Sortable.Coordinates.topLeftOffset(a).reposition(a));var d=this;this.Func_DragInit=function(a){d._dragInit.call(d,
a||event)};this.Func_Drag=function(a){d._drag.call(d,a||event)};this.Func_DragEnd=function(a){d._dragEnd.call(d,a||event)};this.setHandle(b);this.Sortable.transparent&&this.transparentDrag();this.Sortable.classWhenDragging&&this.dragWithClass(this.Sortable.classWhenDragging);this.Sortable.classAfterDragged&&this.draggedWithClass(this.Sortable.classAfterDragged);if(!this.Sortable.isTableMode)this.onTopWhileDragging();return this};
Sortable.Group.prototype={setHandle:function(a){Sortable.events.register(a,"mousedown",this.Func_DragInit);a.onmousedown=function(){return!1};this.element!=a&&Sortable.events.unregister(this.element,"mousedown",this.Func_DragInit)},register:function(a,b){this._listeners[a].push(b)},addTransform:function(a){this._transforms.push(a)},lockToVertical:function(){this.addTransform(Sortable.Constraints.vertical())},lockToHorizontal:function(){this.addTransform(Sortable.Constraints.horizontal())},lockToRegion:function(a,
b,c,d){var e=new Sortable.Coordinate(a,b),f=new Sortable.Coordinate(c,d);this.addTransform(function(a){return a.constrainTo(e,f)})},setThreshold:function(a){this._thresholdDistance=a},transparentDrag:function(a){var a="undefined"!=typeof a?a:0.75,b=Sortable.utility.readCssStyle(this.element,"opacity");this.register("dragstart",function(b){b=b.group.element;b.style.opacity=a;b.style.filter="alpha(opacity="+100*a+")"});this.register("dragend",function(a){a=a.group.element;a.style.opacity=b;var d=document.createElement("span");
a.style.filter=d.style.filter;delete d})},dragWithClass:function(a){var b=this.element.className;this.register("dragstart",function(b){b.group.element.className+=" "+a});this.register("dragend",function(a){a.group.element.className=b})},draggedWithClass:function(a){this.register("dragend",function(b){b=b.group.element;if(""===a)b.className="";else{for(var c=b.className.split(" "),d=0;d<c.length;d++)if(c[d]===a)return;b.className+=" "+a}})},onTopWhileDragging:function(a){var a="undefined"!=typeof a?
a:1E5,b=Sortable.utility.readCssStyle(this.element,"z-index");this.register("dragstart",function(b){b.group.element.style.zIndex=a});this.register("dragend",function(a){try{a.group.element.style.zIndex=b}catch(d){}})},_dragInit:function(a){a=Sortable.events.fix(a);if(a.target!=this._handle&&Sortable.utility.isFormElement(a.target))return!1;a=new Sortable.Event("draginit",a,this);this._isThresholdExceeded=!1;this._initialMouseOffset=a.mouseOffset;this._grabOffset=a.mouseOffset.minus(a.topLeftOffset);
Sortable.events.register(document,"mousemove",this.Func_Drag);this._bakDocumentMouseMove=document.onmousemove;document.onmousemove=function(){return!1};Sortable.events.register(document,"mouseup",this.Func_DragEnd);this._notifyListeners(a)},_drag:function(a){var a=Sortable.events.fix(a),b=new Sortable.Event("dragmove",a,this),c=b.mouseOffset.minus(this._grabOffset);if(!this._isThresholdExceeded){if(b.mouseOffset.distance(this._initialMouseOffset)<this._thresholdDistance)return;this._isThresholdExceeded=
!0;this._notifyListeners(new Sortable.Event("dragstart",a,this))}for(i=0;i<this._transforms.length;i++)c=(0,this._transforms[i])(c,b);a=c.minus(b.topLeftOffset);a=b.topLeftPosition.plus(a);this.Sortable.isTableMode||a.reposition(this.element);b.transformedMouseOffset=c.plus(this._grabOffset);this._notifyListeners(b);this.Sortable.isTableMode||(b=c.minus(Sortable.Coordinates.topLeftOffset(this.element)),(0!=b.x||0!=b.y)&&Sortable.Coordinates.topLeftPosition(this.element).plus(b).reposition(this.element))},
_dragEnd:function(a){a=Sortable.events.fix(a);a=new Sortable.Event("dragend",a,this);this._notifyListeners(a);Sortable.events.unregister(document,"mousemove",this.Func_Drag);document.onmousemove=this._bakDocumentMouseMove;Sortable.events.unregister(document,"mouseup",this.Func_DragEnd)},_notifyListeners:function(a){var b=this._listeners[a.type];for(i=0;i<b.length;i++)b[i](a)}};
Sortable.Event=function(a,b,c){this.type=a;this.group=c;this.mousePosition=Sortable.Coordinates.mousePosition(b);this.transformedMouseOffset=this.mouseOffset=Sortable.Coordinates.mouseOffset(b);this.topLeftPosition=Sortable.Coordinates.topLeftPosition(c.element);this.topLeftOffset=Sortable.Coordinates.topLeftOffset(c.element)};
Sortable.Dumper={serialize:function(a){for(var a=a.list,b=[],c=0,d=a.length;c<d;c++)b.push(this.findId(a[c]));return b.join("|")},findId:function(a){var b=this.trim(a.getAttribute("itemId"));if(null!=b&&0<b.length)return b;b=this.trim(a.getAttribute("id"));return null!=b&&0<b.length?b:void 0!==a.innerText?this.trim(a.innerText):void 0!==a.textContent?this.trim(a.textContent):-1},trim:function(a){return null===a||void 0===a?null:a.replace(/^(\s+)?(.*\S)(\s+)?$/,"$2")}};
Sortable.Constraints={vertical:function(){return function(a,b){var c=b.topLeftOffset.x;return a.x!=c?Sortable.Coordinates.create(c,a.y):a}},horizontal:function(){return function(a,b){var c=b.topLeftOffset.y;return a.y!=c?Sortable.Coordinates.create(a.x,c):a}},region:function(a,b,c,d){var e=Sortable.Coordinates.create(a,b),f=Sortable.Coordinates.create(c,d);return function(a){return a.constrainTo(e,f)}}};
Sortable.Coordinates={create:function(a,b){return new Sortable.Coordinate(a,b)},offset:function(a){return this.create(a.offsetLeft,a.offsetTop)},size:function(a){return this.create(a.offsetWidth,a.offsetHeight)},topLeftOffset:function(a){for(var b=this.offset(a),a=a.offsetParent;a;)b=b.plus(this.offset(a)),a=a.offsetParent;return b},bottomRightOffset:function(a){return this.topLeftOffset(a).plus(this.create(a.offsetWidth,a.offsetHeight))},topLeftPosition:function(a){var b=parseInt(Sortable.utility.readCssStyle(a,
"left")),b=isNaN(b)?0:b,a=parseInt(Sortable.utility.readCssStyle(a,"top")),a=isNaN(a)?0:a;return this.create(b,a)},bottomRightPosition:function(a){return this.topLeftPosition(a).plus(this.size(a))},mousePosition:function(a){a=Sortable.events.fix(a);return this.create(a.clientX,a.clientY)},mouseOffset:function(a){for(var a=Sortable.events.fix(a),b=a.toElement||a.target,c=0,d=0;null!=b&&b!=document.body;)c-=b.scrollLeft||0,d-=b.scrollTop||0,b=b.parentNode;if(0<=a.pageX||0>a.pageX)return this.create(a.pageX-
c,a.pageY-d);if(0<=a.clientX||0>a.clientX)return this.mousePosition(a).plus(this.scrollOffset().minus(this.create(c,d)))},scrollOffset:function(){return window.pageXOffset?this.create(window.pageXOffset,window.pageYOffset):document.documentElement?this.create(document.body.scrollLeft+document.documentElement.scrollLeft,document.body.scrollTop+document.documentElement.scrollTop):0<=document.body.scrollLeft?this.create(document.body.scrollLeft,document.body.scrollTop):this.create(0,0)}};
Sortable.Coordinate=function(a,b){this.x=isNaN(a)?0:a;this.y=isNaN(b)?0:b;return this};
Sortable.Coordinate.prototype={create:function(a,b){return new Sortable.Coordinate(a,b)},origin:function(){return this.create(0,0)},plus:function(a){return this.create(this.x+a.x,this.y+a.y)},minus:function(a){return this.create(this.x-a.x,this.y-a.y)},min:function(a){return this.create(Math.min(this.x,a.x),Math.min(this.y,a.y))},max:function(a){return this.create(Math.max(this.x,a.x),Math.max(this.y,a.y))},constrainTo:function(a,b){var c=a.min(b),d=a.max(b);return this.max(c).min(d)},distance:function(a){return Math.sqrt(Math.pow(this.x-
a.x,2)+Math.pow(this.y-a.y,2))},reposition:function(a){a.style.top=this.y+"px";a.style.left=this.x+"px"},toString:function(){return"["+this.x+","+this.y+"]"}};
Sortable.events={fix:function(a){a||(a=window.event);a.target?3==a.target.nodeType&&(a.target=a.target.parentNode):a.srcElement&&(a.target=a.srcElement);return a},register:function(a,b,c){if(a.addEventListener)a.addEventListener(b,c,!1);else if(a.attachEvent){a._listeners||(a._listeners=[]);a._listeners[b]||(a._listeners[b]=[]);var d=function(){c.apply(a,[])};a._listeners[b][c]=d;a.attachEvent("on"+b,d)}},unregister:function(a,b,c){a.removeEventListener?a.removeEventListener(b,c,!1):a.detachEvent&&
(a._listeners&&a._listeners[b]&&a._listeners[b][c])&&(a.detachEvent("on"+b,a._listeners[b][c]),delete a._listeners[b][c])}};
Sortable.utility={hasClass:function(a,b){if(null===b||void 0===b)return!0;if(""===b)return a.className&&0<a.className.length?!1:!0;if(void 0===a.className||""==a.className.length)return!1;for(var c=a.className.split(" "),d=0,e=c.length;d<e;d++)if(c[d]==b)return!0;return!1},findChild:function(a,b,c){for(var d,e=0,f=a.childNodes.length;e<f;e++){d=a.childNodes[e];if(0<b.length){if(d.tagName==b&&this.hasClass(d,c))return d}else if(this.hasClass(d,c))return d;if(d=this.findChild(d,b,c))return d}return null},
findChildren:function(a,b,c,d){null==d&&(d=[]);for(var e,f=0,g=a.childNodes.length;f<g;f++)if(e=a.childNodes[f],!e.getAttribute||!e.getAttribute("locksort")){if(0<b.length){if(e.tagName==b&&this.hasClass(e,c)){d.push(e);continue}}else if(this.hasClass(e,c)){d.push(e);continue}d=this.findChildren(e,b,c,d)}return d},readCssStyle:function(a,b){return a.style[b]?a.style[b]:a.currentStyle?a.currentStyle[b]:document.defaultView&&document.defaultView.getComputedStyle?document.defaultView.getComputedStyle(a,
null).getPropertyValue(b):null},map:function(a,b){for(var c=0,d=a.length;c<d;c++)b(a[c])},nextItem:function(a,b){if(null!=a){for(var c=a.nextSibling;null!=c;){if(c.nodeName==b)return c;c=c.nextSibling}return null}},previousItem:function(a,b){for(var c=a.previousSibling;null!=c;){if(c.nodeName==b)return c;c=c.previousSibling}return null},moveBefore:function(a,b,c,d){if(1!=a.length){var e=c;null==e&&(e=a[a.length-1].nextSibling);if(e!=b){var f=b.parentNode;f.removeChild(b);f.insertBefore(b,e);this.removeFromList(a,
b);this.insertToList(a,b,c,0,!1);d&&f.insertBefore(f.childNodes[0],f.childNodes[0])}}},removeFromList:function(a,b){for(var c=0,d=a.length;c<d;c++)if(a[c]==b){a.splice(c,1);break}},insertToList:function(a,b,c,d,e){if(null==c)a.splice(e?0:a.length,0,b);else for(var e=0,f=a.length;e<f;e++)if(a[e]==c){a.splice(e+d,0,b);break}},moveAfter:function(a,b,c){if(1!=a.length){var d=b.parentNode;d.removeChild(b);d.insertBefore(b,c?c.nextSibling:null);this.removeFromList(a,b);this.insertToList(a,b,c,1,!0)}},isFormElement:function(a){switch(a.tagName){case "A":case "BUTTON":case "INPUT":case "SELECT":case "OPTION":return!0}return!1}};
